var searchData=
[
  ['badgatewayexception_0',['BadGatewayException',['../class_fauna_1_1_exceptions_1_1_bad_gateway_exception.html',1,'Fauna::Exceptions']]],
  ['baseclient_1',['BaseClient',['../class_fauna_1_1_base_client.html',1,'Fauna']]],
  ['basefieldattribute_2',['BaseFieldAttribute',['../class_fauna_1_1_mapping_1_1_base_field_attribute.html',1,'Fauna::Mapping']]],
  ['baseref_3',['BaseRef',['../class_fauna_1_1_types_1_1_base_ref.html',1,'Fauna::Types']]],
  ['baserefbuilder_4',['BaseRefBuilder',['../class_fauna_1_1_types_1_1_base_ref_builder.html',1,'Fauna::Types']]],
  ['baseserializer_5',['BaseSerializer',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20baseref_3c_20t_20_3e_20_3e_6',['BaseSerializer&lt; BaseRef&lt; T &gt; &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20bool_20_3e_7',['BaseSerializer&lt; bool &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20byte_20_3e_8',['BaseSerializer&lt; byte &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20byte_5b_5d_3e_9',['BaseSerializer&lt; byte[]&gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20dateonly_20_3e_10',['BaseSerializer&lt; DateOnly &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20datetime_20_3e_11',['BaseSerializer&lt; DateTime &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20datetimeoffset_20_3e_12',['BaseSerializer&lt; DateTimeOffset &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20dictionary_3c_20string_2c_20t_20_3e_20_3e_13',['BaseSerializer&lt; Dictionary&lt; string, T &gt; &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20double_20_3e_14',['BaseSerializer&lt; double &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20float_20_3e_15',['BaseSerializer&lt; float &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20int_20_3e_16',['BaseSerializer&lt; int &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20list_3c_20t_20_3e_20_3e_17',['BaseSerializer&lt; List&lt; T &gt; &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20long_20_3e_18',['BaseSerializer&lt; long &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20module_20_3e_19',['BaseSerializer&lt; Module &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20namedref_3c_20t_20_3e_20_3e_20',['BaseSerializer&lt; NamedRef&lt; T &gt; &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20o_20_3e_21',['BaseSerializer&lt; O &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20object_3f_3e_22',['BaseSerializer&lt; object?&gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20object_3f_5b_5d_3e_23',['BaseSerializer&lt; object?[]&gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20page_3c_20t_20_3e_20_3e_24',['BaseSerializer&lt; Page&lt; T &gt; &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20query_20_3e_25',['BaseSerializer&lt; Query &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20queryarr_20_3e_26',['BaseSerializer&lt; QueryArr &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20queryexpr_20_3e_27',['BaseSerializer&lt; QueryExpr &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20queryliteral_20_3e_28',['BaseSerializer&lt; QueryLiteral &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20queryobj_20_3e_29',['BaseSerializer&lt; QueryObj &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20ref_3c_20t_20_3e_20_3e_30',['BaseSerializer&lt; Ref&lt; T &gt; &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20sbyte_20_3e_31',['BaseSerializer&lt; sbyte &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20short_20_3e_32',['BaseSerializer&lt; short &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20stream_20_3e_33',['BaseSerializer&lt; Stream &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20string_3f_3e_34',['BaseSerializer&lt; string?&gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20t_3f_3e_35',['BaseSerializer&lt; T?&gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20uint_20_3e_36',['BaseSerializer&lt; uint &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20ushort_20_3e_37',['BaseSerializer&lt; ushort &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]]
];
