.TH "Fauna/Core Directory Reference" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Core Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBConnection\&.cs\fP"
.br
.ti -1c
.RI "file \fBEndpoints\&.cs\fP"
.br
.ti -1c
.RI "file \fBErrorInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBHeaders\&.cs\fP"
.br
.ti -1c
.RI "file \fBIConnection\&.cs\fP"
.br
.ti -1c
.RI "file \fBQueryOptions\&.cs\fP"
.br
.ti -1c
.RI "file \fBQueryResponse\&.cs\fP"
.br
.ti -1c
.RI "file \fBQueryStats\&.cs\fP"
.br
.ti -1c
.RI "file \fBResponseFields\&.cs\fP"
.br
.ti -1c
.RI "file \fBRetryConfiguration\&.cs\fP"
.br
.ti -1c
.RI "file \fBStatsCollector\&.cs\fP"
.br
.ti -1c
.RI "file \fBStreamEnumerable\&.cs\fP"
.br
.ti -1c
.RI "file \fBStreamOptions\&.cs\fP"
.br
.in -1c
