.TH "Fauna/Util/Extensions Directory Reference" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Util/Extensions Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBPaginationExtensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBTypeExtensions\&.cs\fP"
.br
.in -1c
