.TH "Fauna/Serialization Directory Reference" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Serialization Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBaseRefSerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBClassSerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBDictionarySerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBDynamicSerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBIPartialDocumentSerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBISerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBListSerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBModuleSerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBNullableSerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBNullableStructSerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBPageSerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBQueryArrSerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBQueryExprSerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBQueryLiteralSerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBQueryObjSerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBQuerySerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBQueryValSerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBSerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBStreamSerializer\&.cs\fP"
.br
.ti -1c
.RI "file \fBStructSerializers\&.cs\fP"
.br
.ti -1c
.RI "file \fBTokenType\&.cs\fP"
.br
.ti -1c
.RI "file \fBUtf8FaunaReader\&.cs\fP"
.br
.ti -1c
.RI "file \fBUtf8FaunaWriter\&.cs\fP"
.br
.in -1c
