.TH "Fauna/obj/Debug/net6.0 Directory Reference" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/obj/Debug/net6.0 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.NETCoreApp,Version=v6\&.0\&.AssemblyAttributes\&.cs\fP"
.br
.ti -1c
.RI "file \fBFauna\&.AssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBFauna\&.GlobalUsings\&.g\&.cs\fP"
.br
.in -1c
