.TH "Fauna/Exceptions Directory Reference" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Exceptions Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAbortException\&.cs\fP"
.br
.ti -1c
.RI "file \fBAuthenticationException\&.cs\fP"
.br
.ti -1c
.RI "file \fBAuthorizationException\&.cs\fP"
.br
.ti -1c
.RI "file \fBBadGatewayException\&.cs\fP"
.br
.ti -1c
.RI "file \fBConstraintFailure\&.cs\fP"
.br
.ti -1c
.RI "file \fBConstraintFailureException\&.cs\fP"
.br
.ti -1c
.RI "file \fBContendedTransactionException\&.cs\fP"
.br
.ti -1c
.RI "file \fBExceptionHandler\&.cs\fP"
.br
.ti -1c
.RI "file \fBFaunaException\&.cs\fP"
.br
.ti -1c
.RI "file \fBInvalidRequestException\&.cs\fP"
.br
.ti -1c
.RI "file \fBIRetryableException\&.cs\fP"
.br
.ti -1c
.RI "file \fBNetworkException\&.cs\fP"
.br
.ti -1c
.RI "file \fBNullDocumentException\&.cs\fP"
.br
.ti -1c
.RI "file \fBProtocolException\&.cs\fP"
.br
.ti -1c
.RI "file \fBQueryCheckException\&.cs\fP"
.br
.ti -1c
.RI "file \fBQueryRuntimeException\&.cs\fP"
.br
.ti -1c
.RI "file \fBQueryTimeoutException\&.cs\fP"
.br
.ti -1c
.RI "file \fBSerializationException\&.cs\fP"
.br
.ti -1c
.RI "file \fBServiceException\&.cs\fP"
.br
.ti -1c
.RI "file \fBThrottlingException\&.cs\fP"
.br
.ti -1c
.RI "file \fBTimeoutException\&.cs\fP"
.br
.in -1c
