.TH "Fauna/Exceptions/AbortException.cs" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Exceptions/AbortException.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFauna\&.Exceptions\&.AbortException\fP"
.br
.RI "Represents an exception that occurs when the FQL \fRabort\fP function is called\&. This exception captures the data provided during the abort operation\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFauna\fP"
.br
.ti -1c
.RI "namespace \fBFauna\&.Exceptions\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
