.TH "Fauna/Mapping/Attributes.cs" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Mapping/Attributes.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFauna\&.Mapping\&.ObjectAttribute\fP"
.br
.RI "Attribute used to indicate that a class represents a \fBFauna\fP document or struct\&. "
.ti -1c
.RI "class \fBFauna\&.Mapping\&.IgnoreAttribute\fP"
.br
.RI "Attribute used to indicate that a field should be ignored during serialization and deserialization\&. "
.ti -1c
.RI "class \fBFauna\&.Mapping\&.BaseFieldAttribute\fP"
.br
.ti -1c
.RI "class \fBFauna\&.Mapping\&.FieldAttribute\fP"
.br
.RI "Attribute used to specify fields on a \fBFauna\fP document or struct\&. "
.ti -1c
.RI "class \fBFauna\&.Mapping\&.IdAttribute\fP"
.br
.RI "Attribute used to specify the id field on a \fBFauna\fP document\&. The associated field will be ignored during serialization unless isClientGenerated is set to true\&. "
.ti -1c
.RI "class \fBFauna\&.Mapping\&.CollectionAttribute\fP"
.br
.RI "Attribute used to specify the coll (Collection) field on a \fBFauna\fP document\&. The associated field will be ignored during serialization\&. "
.ti -1c
.RI "class \fBFauna\&.Mapping\&.TsAttribute\fP"
.br
.RI "Attribute used to specify the ts field on a \fBFauna\fP document\&. The associated field will be ignored during serialization\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFauna\fP"
.br
.ti -1c
.RI "namespace \fBFauna\&.Mapping\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
