.TH "Fauna/Serialization/FaunaType.cs" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Serialization/FaunaType.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFauna\fP"
.br
.ti -1c
.RI "namespace \fBFauna\&.Serialization\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFauna\&.Serialization\&.FaunaType\fP { \fBFauna\&.Serialization\&.Int\fP, \fBFauna\&.Serialization\&.Long\fP, \fBFauna\&.Serialization\&.Double\fP, \fBFauna\&.Serialization\&.String\fP, \fBFauna\&.Serialization\&.Date\fP, \fBFauna\&.Serialization\&.Time\fP, \fBFauna\&.Serialization\&.Boolean\fP, \fBFauna\&.Serialization\&.Object\fP, \fBFauna\&.Serialization\&.Ref\fP, \fBFauna\&.Serialization\&.Document\fP, \fBFauna\&.Serialization\&.Array\fP, \fBFauna\&.Serialization\&.Bytes\fP, \fBFauna\&.Serialization\&.Null\fP, \fBFauna\&.Serialization\&.Stream\fP, \fBFauna\&.Serialization\&.Module\fP, \fBFauna\&.Serialization\&.Set\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
