.TH "Fauna.Exceptions.AuthorizationException" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Exceptions.AuthorizationException \- Represents an exception thrown when access to a resource is not allowed\&. Corresponds to the 'forbidden' error code in \fBFauna\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFauna\&.Exceptions\&.ServiceException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAuthorizationException\fP (string message, \fBQueryFailure\fP failure)"
.br
.in -1c

Public Member Functions inherited from \fBFauna\&.Exceptions\&.ServiceException\fP
.in +1c
.ti -1c
.RI "\fBServiceException\fP (string message)"
.br
.RI "Initializes a new instance of the \fBServiceException\fP class with a specified query failure details and error message\&. "
.ti -1c
.RI "\fBServiceException\fP (string message, \fBQueryFailure\fP failure)"
.br
.RI "Initializes a new instance of the \fBServiceException\fP class with a specified query failure details and error message\&. "
.in -1c

Public Member Functions inherited from \fBFauna\&.Exceptions\&.FaunaException\fP
.in +1c
.ti -1c
.RI "\fBFaunaException\fP ()"
.br
.ti -1c
.RI "\fBFaunaException\fP (string message)"
.br
.ti -1c
.RI "\fBFaunaException\fP (string message, Exception innerException)"
.br
.ti -1c
.RI "\fBFaunaException\fP (\fBErrorInfo\fP err)"
.br
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBFauna\&.Exceptions\&.ServiceException\fP
.in +1c
.ti -1c
.RI "string? \fBErrorCode\fP\fR [get]\fP"
.br
.RI "The error code when a query fails\&. "
.ti -1c
.RI "IDictionary< string, string > \fBQueryTags\fP\fR [get]\fP"
.br
.RI "The tags on the x-query-tags header, if it was provided\&. "
.ti -1c
.RI "long? \fBSchemaVersion\fP\fR [get]\fP"
.br
.RI "The schema version used by the query\&. This can be used by clients displaying schema to determine when they should refresh their schema\&. If the schema version that a client has stored differs from the one returned by the query, schema should be refreshed\&. "
.ti -1c
.RI "\fBQueryStats\fP \fBStats\fP\fR [get]\fP"
.br
.RI "The query stats for the request\&. "
.ti -1c
.RI "HttpStatusCode? \fBStatusCode\fP\fR [get, set]\fP"
.br
.RI "The HTTP status code\&. "
.ti -1c
.RI "string? \fBSummary\fP\fR [get]\fP"
.br
.RI "A comprehensive, human readable summary of any errors, warnings and/or logs returned from the query\&. "
.ti -1c
.RI "long? \fBTxnTs\fP\fR [get]\fP"
.br
.RI "The transaction commit time in micros since epoch\&. Used by drivers to populate the x-last-txn-ts request header in order to get a consistent prefix RYOW guarantee\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents an exception thrown when access to a resource is not allowed\&. Corresponds to the 'forbidden' error code in \fBFauna\fP\&. 
.PP
Definition at line \fB9\fP of file \fBAuthorizationException\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fauna\&.Exceptions\&.AuthorizationException\&.AuthorizationException (string message, \fBQueryFailure\fP failure)"

.PP
Definition at line \fB11\fP of file \fBAuthorizationException\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
