.TH "Fauna.IQueryFragment" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.IQueryFragment \- Represents the base interface for a query fragment used for FQL query construction\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBFauna\&.Query\fP, , \fBFauna\&.QueryExpr\fP, \fBFauna\&.QueryLiteral\fP, and \fBFauna\&.QueryObj\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSerialize\fP (\fBMappingContext\fP ctx, \fBUtf8FaunaWriter\fP writer)"
.br
.RI "Serializes the query fragment into the provided stream\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents the base interface for a query fragment used for FQL query construction\&. 
.PP
Definition at line \fB10\fP of file \fBIQueryFragment\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Fauna\&.IQueryFragment\&.Serialize (\fBMappingContext\fP ctx, \fBUtf8FaunaWriter\fP writer)"

.PP
Serializes the query fragment into the provided stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIctx\fP The context to be used during serialization\&.
.br
\fIwriter\fP The writer to which the query fragment is serialized\&.
.RE
.PP

.PP
Implemented in \fBFauna\&.Query\fP, \fBFauna\&.QueryExpr\fP, \fBFauna\&.QueryLiteral\fP, \fBFauna\&.QueryObj\fP, and \fBFauna\&.QueryVal\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
