.TH "Fauna.Mapping.CollectionAttribute" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Mapping.CollectionAttribute \- Attribute used to specify the coll (Collection) field on a \fBFauna\fP document\&. The associated field will be ignored during serialization\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFauna\&.Mapping\&.BaseFieldAttribute\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCollectionAttribute\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBFauna\&.Mapping\&.BaseFieldAttribute\fP
.in +1c
.ti -1c
.RI "readonly? string \fBName\fP"
.br
.ti -1c
.RI "\fBFieldType\fP \fBType\fP"
.br
.in -1c

Protected Member Functions inherited from \fBFauna\&.Mapping\&.BaseFieldAttribute\fP
.in +1c
.ti -1c
.RI "\fBBaseFieldAttribute\fP (string? name, \fBFieldType\fP type)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Attribute used to specify the coll (Collection) field on a \fBFauna\fP document\&. The associated field will be ignored during serialization\&. 
.PP
Definition at line \fB65\fP of file \fBAttributes\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fauna\&.Mapping\&.CollectionAttribute\&.CollectionAttribute ()"

.PP
Definition at line \fB69\fP of file \fBAttributes\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
