.TH "Fauna.Configuration" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Configuration \- \fBConfiguration\fP is a class used to configure a \fBFauna\fP \fBClient\fP\&. It encapsulates various settings such as the \fBEndpoint\fP, secret, query timeout, and others\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfiguration\fP (string secret='', \fBHttpClient\fP? httpClient=null, ILogger? logger=null)"
.br
.RI "Initializes a new instance of the \fBConfiguration\fP record with the specified secret key\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBDisposeHttpClient\fP = true\fR [get]\fP"
.br
.RI "Whether the \fBClient\fP should dispose of the \fBHttpClient\fP on Dispose\&. "
.ti -1c
.RI "HttpClient \fBHttpClient\fP = new HttpClient { Timeout = TimeSpan\&.FromSeconds(5) }\fR [get]\fP"
.br
.RI "The HTTP \fBClient\fP to use for requests\&. "
.ti -1c
.RI "string \fBSecret\fP = Environment\&.GetEnvironmentVariable('FAUNA_SECRET') ?? string\&.Empty\fR [get]\fP"
.br
.RI "The secret key used for authentication\&. "
.ti -1c
.RI "Uri \fBEndpoint\fP = Endpoints\&.GetFaunaEndpoint()\fR [get]\fP"
.br
.RI "The endpoint URL of the \fBFauna\fP server\&. "
.ti -1c
.RI "\fBQueryOptions\fP? \fBDefaultQueryOptions\fP = null\fR [get]\fP"
.br
.RI "Default options for queries sent to \fBFauna\fP\&. "
.ti -1c
.RI "\fBRetryConfiguration\fP \fBRetryConfiguration\fP = new(3, TimeSpan\&.FromSeconds(20))\fR [get]\fP"
.br
.RI "The retry configuration to apply to requests\&. "
.ti -1c
.RI "\fBIStatsCollector\fP? \fBStatsCollector\fP = new \fBStatsCollector\fP()\fR [get]\fP"
.br
.RI "StatsCollector for the client\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBConfiguration\fP is a class used to configure a \fBFauna\fP \fBClient\fP\&. It encapsulates various settings such as the \fBEndpoint\fP, secret, query timeout, and others\&. 
.PP
Definition at line \fB11\fP of file \fBConfiguration\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fauna\&.Configuration\&.Configuration (string secret = \fR''\fP, \fBHttpClient\fP? httpClient = \fRnull\fP, ILogger? logger = \fRnull\fP)"

.PP
Initializes a new instance of the \fBConfiguration\fP record with the specified secret key\&. 
.PP
\fBParameters\fP
.RS 4
\fIsecret\fP The secret key used for authentication\&.
.br
\fIhttpClient\fP The \fBHttpClient\fP to use\&.
.RE
.PP

.PP
Definition at line \fB54\fP of file \fBConfiguration\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBQueryOptions\fP? Fauna\&.Configuration\&.DefaultQueryOptions = null\fR [get]\fP"

.PP
Default options for queries sent to \fBFauna\fP\&. 
.PP
Definition at line \fB36\fP of file \fBConfiguration\&.cs\fP\&.
.SS "bool Fauna\&.Configuration\&.DisposeHttpClient = true\fR [get]\fP"

.PP
Whether the \fBClient\fP should dispose of the \fBHttpClient\fP on Dispose\&. 
.PP
Definition at line \fB16\fP of file \fBConfiguration\&.cs\fP\&.
.SS "Uri Fauna\&.Configuration\&.Endpoint = Endpoints\&.GetFaunaEndpoint()\fR [get]\fP"

.PP
The endpoint URL of the \fBFauna\fP server\&. 
.PP
Definition at line \fB31\fP of file \fBConfiguration\&.cs\fP\&.
.SS "HttpClient Fauna\&.Configuration\&.HttpClient = new HttpClient { Timeout = TimeSpan\&.FromSeconds(5) }\fR [get]\fP"

.PP
The HTTP \fBClient\fP to use for requests\&. 
.PP
Definition at line \fB21\fP of file \fBConfiguration\&.cs\fP\&.
.SS "\fBRetryConfiguration\fP Fauna\&.Configuration\&.RetryConfiguration = new(3, TimeSpan\&.FromSeconds(20))\fR [get]\fP"

.PP
The retry configuration to apply to requests\&. 
.PP
Definition at line \fB41\fP of file \fBConfiguration\&.cs\fP\&.
.SS "string Fauna\&.Configuration\&.Secret = Environment\&.GetEnvironmentVariable('FAUNA_SECRET') ?? string\&.Empty\fR [get]\fP"

.PP
The secret key used for authentication\&. 
.PP
Definition at line \fB26\fP of file \fBConfiguration\&.cs\fP\&.
.SS "\fBIStatsCollector\fP? Fauna\&.Configuration\&.StatsCollector = new \fBStatsCollector\fP()\fR [get]\fP"

.PP
StatsCollector for the client\&. 
.PP
Definition at line \fB47\fP of file \fBConfiguration\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
