.TH "Fauna.Exceptions.FaunaException" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Exceptions.FaunaException \- Represents the base exception class for all exceptions specific to \fBFauna\fP interactions\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.PP
Inherited by \fBFauna\&.Exceptions\&.NetworkException\fP, \fBFauna\&.Exceptions\&.ProtocolException\fP, and \fBFauna\&.Exceptions\&.ServiceException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFaunaException\fP ()"
.br
.ti -1c
.RI "\fBFaunaException\fP (string message)"
.br
.ti -1c
.RI "\fBFaunaException\fP (string message, Exception innerException)"
.br
.ti -1c
.RI "\fBFaunaException\fP (\fBErrorInfo\fP err)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents the base exception class for all exceptions specific to \fBFauna\fP interactions\&. 
.PP
Definition at line \fB8\fP of file \fBFaunaException\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fauna\&.Exceptions\&.FaunaException\&.FaunaException ()"

.PP
Definition at line \fB10\fP of file \fBFaunaException\&.cs\fP\&.
.SS "Fauna\&.Exceptions\&.FaunaException\&.FaunaException (string message)"

.PP
Definition at line \fB12\fP of file \fBFaunaException\&.cs\fP\&.
.SS "Fauna\&.Exceptions\&.FaunaException\&.FaunaException (string message, Exception innerException)"

.PP
Definition at line \fB14\fP of file \fBFaunaException\&.cs\fP\&.
.SS "Fauna\&.Exceptions\&.FaunaException\&.FaunaException (\fBErrorInfo\fP err)"

.PP
Definition at line \fB17\fP of file \fBFaunaException\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
