.TH "Fauna.Serialization.Utf8FaunaWriter" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Serialization.Utf8FaunaWriter \- Provides functionality for writing data in a streaming manner to a buffer or a stream\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IAsyncDisposable, and IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUtf8FaunaWriter\fP (IBufferWriter< byte > bufferWriter)"
.br
.RI "Initializes a new instance of the \fBUtf8FaunaWriter\fP class with a specified buffer writer\&. "
.ti -1c
.RI "\fBUtf8FaunaWriter\fP (\fBStream\fP stream)"
.br
.RI "Initializes a new instance of the \fBUtf8FaunaWriter\fP class with a specified stream\&. "
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.RI "Flushes the written data to the underlying buffer or stream\&. "
.ti -1c
.RI "async ValueTask \fBFlushAsync\fP ()"
.br
.RI "Asynchronously flushes the written data to the underlying buffer or stream\&. "
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "Disposes the underlying writer\&. "
.ti -1c
.RI "async ValueTask \fBDisposeAsync\fP ()"
.br
.RI "Asynchronously disposes the underlying writer\&. "
.ti -1c
.RI "void \fBWriteStartObject\fP ()"
.br
.RI "Writes the beginning of an object\&. "
.ti -1c
.RI "void \fBWriteEndObject\fP ()"
.br
.RI "Writes the end of an object\&. "
.ti -1c
.RI "void \fBWriteStartEscapedObject\fP ()"
.br
.RI "Writes the beginning of a specially tagged object\&. "
.ti -1c
.RI "void \fBWriteEndEscapedObject\fP ()"
.br
.RI "Writes the end of a specially tagged object\&. "
.ti -1c
.RI "void \fBWriteStartArray\fP ()"
.br
.RI "Writes the beginning of an array\&. "
.ti -1c
.RI "void \fBWriteEndArray\fP ()"
.br
.RI "Writes the end of an array\&. "
.ti -1c
.RI "void \fBWriteStartRef\fP ()"
.br
.RI "Writes the beginning of a reference object\&. "
.ti -1c
.RI "void \fBWriteEndRef\fP ()"
.br
.RI "Writes the end of a reference object\&. "
.ti -1c
.RI "void \fBWriteDouble\fP (string fieldName, decimal value)"
.br
.RI "Writes a double value with a specific field name\&. "
.ti -1c
.RI "void \fBWriteDouble\fP (string fieldName, double value)"
.br
.RI "Writes a double value with a specific field name\&. "
.ti -1c
.RI "void \fBWriteInt\fP (string fieldName, int value)"
.br
.RI "Writes an integer value with a specific field name\&. "
.ti -1c
.RI "void \fBWriteLong\fP (string fieldName, long value)"
.br
.RI "Writes a long integer value with a specific field name\&. "
.ti -1c
.RI "void \fBWriteBytes\fP (string fieldName, byte[] value)"
.br
.RI "Writes a byte array value with a specific field name\&. "
.ti -1c
.RI "void \fBWriteString\fP (string fieldName, string value)"
.br
.RI "Writes a string value with a specific field name\&. "
.ti -1c
.RI "void \fBWriteDate\fP (string fieldName, DateTime value)"
.br
.RI "Writes a date value with a specific field name\&. "
.ti -1c
.RI "void \fBWriteTime\fP (string fieldName, DateTime value)"
.br
.RI "Writes a time value with a specific field name\&. "
.ti -1c
.RI "void \fBWriteBoolean\fP (string fieldName, bool value)"
.br
.RI "Writes a boolean value with a specific field name\&. "
.ti -1c
.RI "void \fBWriteNull\fP (string fieldName)"
.br
.RI "Writes a null value with a specific field name\&. "
.ti -1c
.RI "void \fBWriteModule\fP (string fieldName, \fBModule\fP value)"
.br
.RI "Writes a module value with a specific field name\&. "
.ti -1c
.RI "void \fBWriteFieldName\fP (string value)"
.br
.RI "Writes a field name for the next value\&. "
.ti -1c
.RI "void \fBWriteTaggedValue\fP (string tag, string value)"
.br
.RI "Writes a tagged value in an object\&. "
.ti -1c
.RI "void \fBWriteDoubleValue\fP (decimal value)"
.br
.RI "Writes a double value as a tagged element\&. "
.ti -1c
.RI "void \fBWriteDoubleValue\fP (double value)"
.br
.RI "Writes a double value as a tagged element\&. "
.ti -1c
.RI "void \fBWriteIntValue\fP (int value)"
.br
.RI "Writes an integer value as a tagged element\&. "
.ti -1c
.RI "void \fBWriteBytesValue\fP (byte[] value)"
.br
.RI "Writes a byte array value as a tagged element\&. "
.ti -1c
.RI "void \fBWriteLongValue\fP (long value)"
.br
.RI "Writes a long integer value as a tagged element\&. "
.ti -1c
.RI "void \fBWriteStringValue\fP (string value)"
.br
.RI "Writes a string value as a tagged element\&. "
.ti -1c
.RI "void \fBWriteDateValue\fP (DateTime value)"
.br
.RI "Writes a date value as a tagged element\&. "
.ti -1c
.RI "void \fBWriteDateValue\fP (DateOnly value)"
.br
.RI "Writes a date value as a tagged element\&. "
.ti -1c
.RI "void \fBWriteDateValue\fP (DateTimeOffset value)"
.br
.RI "Writes a date value as a tagged element\&. "
.ti -1c
.RI "void \fBWriteTimeValue\fP (DateTime value)"
.br
.RI "Writes a date value as a tagged element\&. "
.ti -1c
.RI "void \fBWriteTimeValue\fP (DateTimeOffset value)"
.br
.RI "Writes a date value as a tagged element\&. "
.ti -1c
.RI "void \fBWriteBooleanValue\fP (bool value)"
.br
.RI "Writes a boolean value to the stream\&. "
.ti -1c
.RI "void \fBWriteNullValue\fP ()"
.br
.RI "Writes a null value to the stream\&. "
.ti -1c
.RI "void \fBWriteModuleValue\fP (\fBModule\fP value)"
.br
.RI "Writes a module value as a tagged element\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides functionality for writing data in a streaming manner to a buffer or a stream\&. 
.PP
Definition at line \fB12\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fauna\&.Serialization\&.Utf8FaunaWriter\&.Utf8FaunaWriter (IBufferWriter< byte > bufferWriter)"

.PP
Initializes a new instance of the \fBUtf8FaunaWriter\fP class with a specified buffer writer\&. 
.PP
\fBParameters\fP
.RS 4
\fIbufferWriter\fP The buffer writer to write to\&.
.RE
.PP

.PP
Definition at line \fB20\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "Fauna\&.Serialization\&.Utf8FaunaWriter\&.Utf8FaunaWriter (\fBStream\fP stream)"

.PP
Initializes a new instance of the \fBUtf8FaunaWriter\fP class with a specified stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIstream\fP The stream to write to\&.
.RE
.PP

.PP
Definition at line \fB29\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.Dispose ()"

.PP
Disposes the underlying writer\&. 
.PP
Definition at line \fB53\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "async ValueTask Fauna\&.Serialization\&.Utf8FaunaWriter\&.DisposeAsync ()"

.PP
Asynchronously disposes the underlying writer\&. 
.PP
Definition at line \fB61\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.Flush ()"

.PP
Flushes the written data to the underlying buffer or stream\&. 
.PP
Definition at line \fB37\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "async ValueTask Fauna\&.Serialization\&.Utf8FaunaWriter\&.FlushAsync ()"

.PP
Asynchronously flushes the written data to the underlying buffer or stream\&. 
.PP
Definition at line \fB45\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteBoolean (string fieldName, bool value)"

.PP
Writes a boolean value with a specific field name\&. 
.PP
\fBParameters\fP
.RS 4
\fIfieldName\fP The name of the field\&.
.br
\fIvalue\fP The boolean value to write\&.
.RE
.PP

.PP
Definition at line \fB229\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteBooleanValue (bool value)"

.PP
Writes a boolean value to the stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The boolean value to write\&.
.RE
.PP

.PP
Definition at line \fB386\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteBytes (string fieldName, byte[] value)"

.PP
Writes a byte array value with a specific field name\&. 
.PP
\fBParameters\fP
.RS 4
\fIfieldName\fP The name of the field\&.
.br
\fIvalue\fP The byte array value to write\&.
.RE
.PP

.PP
Definition at line \fB185\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteBytesValue (byte[] value)"

.PP
Writes a byte array value as a tagged element\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The byte array value to write\&.
.RE
.PP

.PP
Definition at line \fB309\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteDate (string fieldName, DateTime value)"

.PP
Writes a date value with a specific field name\&. 
.PP
\fBParameters\fP
.RS 4
\fIfieldName\fP The name of the field\&.
.br
\fIvalue\fP The DateTime value to write\&.
.RE
.PP

.PP
Definition at line \fB207\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteDateValue (DateOnly value)"

.PP
Writes a date value as a tagged element\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The date value to write\&.
.RE
.PP

.PP
Definition at line \fB346\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteDateValue (DateTime value)"

.PP
Writes a date value as a tagged element\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The date value to write\&.
.RE
.PP

.PP
Definition at line \fB336\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteDateValue (DateTimeOffset value)"

.PP
Writes a date value as a tagged element\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The date value to write\&.
.RE
.PP

.PP
Definition at line \fB356\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteDouble (string fieldName, decimal value)"

.PP
Writes a double value with a specific field name\&. 
.PP
\fBParameters\fP
.RS 4
\fIfieldName\fP The name of the field\&.
.br
\fIvalue\fP The decimal value to write\&.
.RE
.PP

.PP
Definition at line \fB141\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteDouble (string fieldName, double value)"

.PP
Writes a double value with a specific field name\&. 
.PP
\fBParameters\fP
.RS 4
\fIfieldName\fP The name of the field\&.
.br
\fIvalue\fP The double value to write\&.
.RE
.PP

.PP
Definition at line \fB152\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteDoubleValue (decimal value)"

.PP
Writes a double value as a tagged element\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The double value to write\&.
.RE
.PP

.PP
Definition at line \fB282\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteDoubleValue (double value)"

.PP
Writes a double value as a tagged element\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The double value to write\&.
.RE
.PP

.PP
Definition at line \fB291\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteEndArray ()"

.PP
Writes the end of an array\&. 
.PP
Definition at line \fB112\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteEndEscapedObject ()"

.PP
Writes the end of a specially tagged object\&. 
.PP
Definition at line \fB95\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteEndObject ()"

.PP
Writes the end of an object\&. 
.PP
Definition at line \fB77\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteEndRef ()"

.PP
Writes the end of a reference object\&. 
.PP
Definition at line \fB130\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteFieldName (string value)"

.PP
Writes a field name for the next value\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The name of the field\&.
.RE
.PP

.PP
Definition at line \fB261\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteInt (string fieldName, int value)"

.PP
Writes an integer value with a specific field name\&. 
.PP
\fBParameters\fP
.RS 4
\fIfieldName\fP The name of the field\&.
.br
\fIvalue\fP The integer value to write\&.
.RE
.PP

.PP
Definition at line \fB163\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteIntValue (int value)"

.PP
Writes an integer value as a tagged element\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The integer value to write\&.
.RE
.PP

.PP
Definition at line \fB300\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteLong (string fieldName, long value)"

.PP
Writes a long integer value with a specific field name\&. 
.PP
\fBParameters\fP
.RS 4
\fIfieldName\fP The name of the field\&.
.br
\fIvalue\fP The long integer value to write\&.
.RE
.PP

.PP
Definition at line \fB174\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteLongValue (long value)"

.PP
Writes a long integer value as a tagged element\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The long integer value to write\&.
.RE
.PP

.PP
Definition at line \fB318\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteModule (string fieldName, \fBModule\fP value)"

.PP
Writes a module value with a specific field name\&. 
.PP
\fBParameters\fP
.RS 4
\fIfieldName\fP The name of the field\&.
.br
\fIvalue\fP The module value to write\&.
.RE
.PP

.PP
Definition at line \fB251\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteModuleValue (\fBModule\fP value)"

.PP
Writes a module value as a tagged element\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The module value to write\&.
.RE
.PP

.PP
Definition at line \fB403\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteNull (string fieldName)"

.PP
Writes a null value with a specific field name\&. 
.PP
\fBParameters\fP
.RS 4
\fIfieldName\fP The name of the field\&.
.RE
.PP

.PP
Definition at line \fB240\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteNullValue ()"

.PP
Writes a null value to the stream\&. 
.PP
Definition at line \fB394\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteStartArray ()"

.PP
Writes the beginning of an array\&. 
.PP
Definition at line \fB104\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteStartEscapedObject ()"

.PP
Writes the beginning of a specially tagged object\&. 
.PP
Definition at line \fB85\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteStartObject ()"

.PP
Writes the beginning of an object\&. 
.PP
Definition at line \fB69\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteStartRef ()"

.PP
Writes the beginning of a reference object\&. 
.PP
Definition at line \fB120\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteString (string fieldName, string value)"

.PP
Writes a string value with a specific field name\&. 
.PP
\fBParameters\fP
.RS 4
\fIfieldName\fP The name of the field\&.
.br
\fIvalue\fP The string value to write\&.
.RE
.PP

.PP
Definition at line \fB196\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteStringValue (string value)"

.PP
Writes a string value as a tagged element\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The string value to write\&.
.RE
.PP

.PP
Definition at line \fB327\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteTaggedValue (string tag, string value)"

.PP
Writes a tagged value in an object\&. 
.PP
\fBParameters\fP
.RS 4
\fItag\fP The tag to use for the value\&.
.br
\fIvalue\fP The value associated with the tag\&.
.RE
.PP

.PP
Definition at line \fB271\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteTime (string fieldName, DateTime value)"

.PP
Writes a time value with a specific field name\&. 
.PP
\fBParameters\fP
.RS 4
\fIfieldName\fP The name of the field\&.
.br
\fIvalue\fP The DateTime value to write\&.
.RE
.PP

.PP
Definition at line \fB218\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteTimeValue (DateTime value)"

.PP
Writes a date value as a tagged element\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The date value to write\&.
.RE
.PP

.PP
Definition at line \fB366\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaWriter\&.WriteTimeValue (DateTimeOffset value)"

.PP
Writes a date value as a tagged element\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The date value to write\&.
.RE
.PP

.PP
Definition at line \fB376\fP of file \fBUtf8FaunaWriter\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
