.TH "Fauna.Serialization.BaseSerializer< T >" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Serialization.BaseSerializer< T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFauna\&.Serialization\&.ISerializer< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual List< \fBFaunaType\fP > \fBGetSupportedTypes\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBFauna\&.Serialization\&.ISerializer< T >\fP
.in +1c
.ti -1c
.RI "new T \fBDeserialize\fP (\fBMappingContext\fP context, ref \fBUtf8FaunaReader\fP reader)"
.br
.ti -1c
.RI "object? \fBDeserialize\fP (\fBMappingContext\fP context, ref \fBUtf8FaunaReader\fP reader)"
.br
.ti -1c
.RI "void \fBSerialize\fP (\fBMappingContext\fP ctx, \fBUtf8FaunaWriter\fP w, object? o)"
.br
.ti -1c
.RI "List< \fBFaunaType\fP > \fBGetSupportedTypes\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "string \fBUnexpectedTokenExceptionMessage\fP (\fBTokenType\fP token)"
.br
.ti -1c
.RI "string \fBUnsupportedSerializationTypeMessage\fP (Type type)"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static \fBTokenType\fP \fBEndTokenFor\fP (\fBTokenType\fP start)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBISerializer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBTokenType\fP \fBFauna\&.Serialization\&.BaseSerializer\fP< T >\&.EndTokenFor (\fBTokenType\fP start)\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB22\fP of file \fBISerializer\&.cs\fP\&.
.SS "virtual List< \fBFaunaType\fP > \fBFauna\&.Serialization\&.BaseSerializer\fP< T >\&.GetSupportedTypes ()\fR [virtual]\fP"

.SS "string \fBFauna\&.Serialization\&.BaseSerializer\fP< T >\&.UnexpectedTokenExceptionMessage (\fBTokenType\fP token)\fR [protected]\fP"

.SS "string \fBFauna\&.Serialization\&.BaseSerializer\fP< T >\&.UnsupportedSerializationTypeMessage (Type type)\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
