.TH "Fauna.Mapping.MappingInfo" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Mapping.MappingInfo \- A class that encapsulates the class mapping, serialization, and deserialization of a \fBFauna\fP object, including documents\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "Type \fBType\fP\fR [get]\fP"
.br
.RI "The associated type\&. "
.ti -1c
.RI "IReadOnlyList< \fBFieldInfo\fP > \fBFields\fP\fR [get]\fP"
.br
.RI "A read-only list of \fBFieldInfo\fP representing the object\&. "
.ti -1c
.RI "IReadOnlyDictionary< string, \fBFieldInfo\fP > \fBFieldsByName\fP\fR [get]\fP"
.br
.RI "A read-only dictionary of \fBFieldInfo\fP representing the object\&. "
.in -1c
.SH "Detailed Description"
.PP 
A class that encapsulates the class mapping, serialization, and deserialization of a \fBFauna\fP object, including documents\&. 
.PP
Definition at line \fB11\fP of file \fBMappingInfo\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "IReadOnlyList<\fBFieldInfo\fP> Fauna\&.Mapping\&.MappingInfo\&.Fields\fR [get]\fP"

.PP
A read-only list of \fBFieldInfo\fP representing the object\&. 
.PP
Definition at line \fB20\fP of file \fBMappingInfo\&.cs\fP\&.
.SS "IReadOnlyDictionary<string, \fBFieldInfo\fP> Fauna\&.Mapping\&.MappingInfo\&.FieldsByName\fR [get]\fP"

.PP
A read-only dictionary of \fBFieldInfo\fP representing the object\&. 
.PP
Definition at line \fB24\fP of file \fBMappingInfo\&.cs\fP\&.
.SS "Type Fauna\&.Mapping\&.MappingInfo\&.Type\fR [get]\fP"

.PP
The associated type\&. 
.PP
Definition at line \fB16\fP of file \fBMappingInfo\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
