.TH "Fauna.Mapping.ObjectAttribute" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Mapping.ObjectAttribute \- Attribute used to indicate that a class represents a \fBFauna\fP document or struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.SH "Detailed Description"
.PP 
Attribute used to indicate that a class represents a \fBFauna\fP document or struct\&. 
.PP
Definition at line \fB9\fP of file \fBAttributes\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
