.TH "Fauna.Mapping.IgnoreAttribute" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Mapping.IgnoreAttribute \- Attribute used to indicate that a field should be ignored during serialization and deserialization\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIgnoreAttribute\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Attribute used to indicate that a field should be ignored during serialization and deserialization\&. 
.PP
Definition at line \fB17\fP of file \fBAttributes\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fauna\&.Mapping\&.IgnoreAttribute\&.IgnoreAttribute ()"

.PP
Definition at line \fB19\fP of file \fBAttributes\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
