.TH "Fauna.Mapping.IdAttribute" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Mapping.IdAttribute \- Attribute used to specify the id field on a \fBFauna\fP document\&. The associated field will be ignored during serialization unless isClientGenerated is set to true\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFauna\&.Mapping\&.BaseFieldAttribute\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIdAttribute\fP ()"
.br
.ti -1c
.RI "\fBIdAttribute\fP (bool isClientGenerated)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBFauna\&.Mapping\&.BaseFieldAttribute\fP
.in +1c
.ti -1c
.RI "readonly? string \fBName\fP"
.br
.ti -1c
.RI "\fBFieldType\fP \fBType\fP"
.br
.in -1c

Protected Member Functions inherited from \fBFauna\&.Mapping\&.BaseFieldAttribute\fP
.in +1c
.ti -1c
.RI "\fBBaseFieldAttribute\fP (string? name, \fBFieldType\fP type)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Attribute used to specify the id field on a \fBFauna\fP document\&. The associated field will be ignored during serialization unless isClientGenerated is set to true\&. 
.PP
Definition at line \fB50\fP of file \fBAttributes\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fauna\&.Mapping\&.IdAttribute\&.IdAttribute ()"

.PP
Definition at line \fB54\fP of file \fBAttributes\&.cs\fP\&.
.SS "Fauna\&.Mapping\&.IdAttribute\&.IdAttribute (bool isClientGenerated)"

.PP
Definition at line \fB56\fP of file \fBAttributes\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
