.TH "Fauna.Core.Stats" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Core.Stats
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBReadOps\fP\fR [get]\fP"
.br
.ti -1c
.RI "long \fBComputeOps\fP\fR [get]\fP"
.br
.ti -1c
.RI "long \fBWriteOps\fP\fR [get]\fP"
.br
.ti -1c
.RI "long \fBQueryTimeMs\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBContentionRetries\fP\fR [get]\fP"
.br
.ti -1c
.RI "long \fBStorageBytesRead\fP\fR [get]\fP"
.br
.ti -1c
.RI "long \fBStorageBytesWrite\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBQueryCount\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBRateLimitedReadQueryCount\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBRateLimitedComputeQueryCount\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBRateLimitedWriteQueryCount\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBStatsCollector\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "long Fauna\&.Core\&.Stats\&.ComputeOps\fR [get]\fP"

.PP
Definition at line \fB7\fP of file \fBStatsCollector\&.cs\fP\&.
.SS "int Fauna\&.Core\&.Stats\&.ContentionRetries\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBStatsCollector\&.cs\fP\&.
.SS "int Fauna\&.Core\&.Stats\&.QueryCount\fR [get]\fP"

.PP
Definition at line \fB13\fP of file \fBStatsCollector\&.cs\fP\&.
.SS "long Fauna\&.Core\&.Stats\&.QueryTimeMs\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBStatsCollector\&.cs\fP\&.
.SS "int Fauna\&.Core\&.Stats\&.RateLimitedComputeQueryCount\fR [get]\fP"

.PP
Definition at line \fB16\fP of file \fBStatsCollector\&.cs\fP\&.
.SS "int Fauna\&.Core\&.Stats\&.RateLimitedReadQueryCount\fR [get]\fP"

.PP
Definition at line \fB15\fP of file \fBStatsCollector\&.cs\fP\&.
.SS "int Fauna\&.Core\&.Stats\&.RateLimitedWriteQueryCount\fR [get]\fP"

.PP
Definition at line \fB17\fP of file \fBStatsCollector\&.cs\fP\&.
.SS "long Fauna\&.Core\&.Stats\&.ReadOps\fR [get]\fP"

.PP
Definition at line \fB6\fP of file \fBStatsCollector\&.cs\fP\&.
.SS "long Fauna\&.Core\&.Stats\&.StorageBytesRead\fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBStatsCollector\&.cs\fP\&.
.SS "long Fauna\&.Core\&.Stats\&.StorageBytesWrite\fR [get]\fP"

.PP
Definition at line \fB12\fP of file \fBStatsCollector\&.cs\fP\&.
.SS "long Fauna\&.Core\&.Stats\&.WriteOps\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBStatsCollector\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
