.TH "Fauna" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCore\fP"
.br
.ti -1c
.RI "namespace \fBExceptions\fP"
.br
.ti -1c
.RI "namespace \fBLinq\fP"
.br
.ti -1c
.RI "namespace \fBMapping\fP"
.br
.ti -1c
.RI "namespace \fBSerialization\fP"
.br
.ti -1c
.RI "namespace \fBTypes\fP"
.br
.ti -1c
.RI "namespace \fBUtil\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseClient\fP"
.br
.RI "The base class for \fBClient\fP and DataContext\&. "
.ti -1c
.RI "class \fBClient\fP"
.br
.RI "Represents a client for interacting with a \fBFauna\fP\&. "
.ti -1c
.RI "class \fBConfiguration\fP"
.br
.RI "\fBConfiguration\fP is a class used to configure a \fBFauna\fP \fBClient\fP\&. It encapsulates various settings such as the \fBEndpoint\fP, secret, query timeout, and others\&. "
.ti -1c
.RI "interface \fBIClient\fP"
.br
.RI "Represents a client for interacting with a \fBFauna\fP\&. "
.ti -1c
.RI "interface \fBIQueryFragment\fP"
.br
.RI "Represents the base interface for a query fragment used for FQL query construction\&. "
.ti -1c
.RI "class \fBIQueryFragmentExtensions\fP"
.br
.RI "Provides extension methods for the \fBIQueryFragment\fP interface to enhance its functionality, allowing for more flexible serialization options\&. "
.ti -1c
.RI "class \fBQuery\fP"
.br
.RI "Represents the abstract base class for constructing FQL queries\&. "
.ti -1c
.RI "class \fBQueryArr\fP"
.br
.RI "Represents an array of FQL queries\&. "
.ti -1c
.RI "class \fBQueryExpr\fP"
.br
.RI "Represents an FQL query expression\&. This class encapsulates a list of \fBIQueryFragment\fP instances, allowing for complex query constructions\&. "
.ti -1c
.RI "class \fBQueryLiteral\fP"
.br
.RI "Represents a literal part of an FQL query\&. This class is used for embedding raw string values directly into the query structure\&. "
.ti -1c
.RI "class \fBQueryObj\fP"
.br
.RI "Represents a dictionary of FQL queries\&. "
.ti -1c
.RI "struct \fBQueryStringHandler\fP"
.br
.RI "Provides a mechanism to build FQL query expressions using interpolated strings\&. This structure collects fragments and literals to construct complex query expressions\&. "
.ti -1c
.RI "class \fBQueryVal\fP"
.br
.RI "Represents a generic value holder for FQL queries\&. This class allows embedding values of various types into the query, with support for primitives, POCOs, and other types\&. "
.ti -1c
.RI "class \fBStreamOptions\fP"
.br
.RI "Represents the options when subscribing to \fBFauna\fP Streams\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
