.TH "Fauna.Linq.DataContext.NameAttribute" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Linq.DataContext.NameAttribute
.SH SYNOPSIS
.br
.PP
.PP
Inherits Attribute\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNameAttribute\fP (string name)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB64\fP of file \fBDataContext\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fauna\&.Linq\&.DataContext\&.NameAttribute\&.NameAttribute (string name)"

.PP
Definition at line \fB68\fP of file \fBDataContext\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
