.TH "Fauna.QueryVal" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.QueryVal \- Represents a generic value holder for FQL queries\&. This class allows embedding values of various types into the query, with support for primitives, POCOs, and other types\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFauna\&.Query\fP, and \fBFauna\&.IQueryFragment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQueryVal\fP (object? v)"
.br
.RI "Initializes a new instance of the \fBQueryVal\fP class with the specified value\&. "
.ti -1c
.RI "override void \fBSerialize\fP (\fBMappingContext\fP ctx, \fBUtf8FaunaWriter\fP writer)"
.br
.RI "Serializes the query value\&. "
.ti -1c
.RI "override bool \fBEquals\fP (\fBQuery\fP? o)"
.br
.RI "Determines whether the specified \fBQueryVal\fP is equal to the current \fBQueryVal\fP\&. "
.ti -1c
.RI "override bool \fBEquals\fP (object? o)"
.br
.RI "Determines whether the specified object is equal to the current \fBQueryVal\fP\&. "
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.RI "The default hash function\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a string that represents the current \fBQueryVal\fP\&. "
.in -1c

Public Member Functions inherited from \fBFauna\&.Query\fP
.in +1c
.ti -1c
.RI "void \fBSerialize\fP (\fBMappingContext\fP ctx, \fBUtf8FaunaWriter\fP writer)"
.br
.RI "Serializes the query into the provided stream\&. "
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.RI "Returns a hash code for the current query\&. "
.ti -1c
.RI "override bool \fBEquals\fP (object? otherObject)"
.br
.RI "Determines whether the specified object is equal to the current query\&. "
.ti -1c
.RI "bool \fBEquals\fP (\fBQuery\fP? otherQuery)"
.br
.RI "Determines whether the specified \fBQuery\fP is equal to the current query\&. "
.in -1c

Public Member Functions inherited from \fBFauna\&.IQueryFragment\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBoperator==\fP (\fBQueryVal\fP left, \fBQueryVal\fP right)"
.br
.RI "Determines whether two specified instances of \fBQueryVal\fP are equal\&. "
.ti -1c
.RI "static bool \fBoperator!=\fP (\fBQueryVal\fP left, \fBQueryVal\fP right)"
.br
.RI "Determines whether two specified instances of \fBQueryVal\fP are not equal\&. "
.in -1c

Static Public Member Functions inherited from \fBFauna\&.Query\fP
.in +1c
.ti -1c
.RI "static \fBQuery\fP \fBFQL\fP (ref \fBQueryStringHandler\fP handler)"
.br
.RI "Constructs an FQL query using the specified \fBQueryStringHandler\fP\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "object? \fBUnwrap\fP\fR [get]\fP"
.br
.RI "Gets the value of the specified type represented in the query\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a generic value holder for FQL queries\&. This class allows embedding values of various types into the query, with support for primitives, POCOs, and other types\&. 
.PP
Definition at line \fB9\fP of file \fBQueryVal\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fauna\&.QueryVal\&.QueryVal (object? v)"

.PP
Initializes a new instance of the \fBQueryVal\fP class with the specified value\&. 
.PP
\fBParameters\fP
.RS 4
\fIv\fP The value of the specified type to be represented in the query\&.
.RE
.PP

.PP
Definition at line \fB20\fP of file \fBQueryVal\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool Fauna\&.QueryVal\&.Equals (object? o)"

.PP
Determines whether the specified object is equal to the current \fBQueryVal\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIo\fP The object to compare with the current \fBQueryVal\fP\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if the specified object is equal to the current \fBQueryVal\fP; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB52\fP of file \fBQueryVal\&.cs\fP\&.
.SS "override bool Fauna\&.QueryVal\&.Equals (\fBQuery\fP? o)"

.PP
Determines whether the specified \fBQueryVal\fP is equal to the current \fBQueryVal\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIo\fP The \fBQueryVal\fP to compare with the current \fBQueryVal\fP\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if the specified \fBQueryVal\fP is equal to the current \fBQueryVal\fP; otherwise, false\&.
.RE
.PP

.SS "override int Fauna\&.QueryVal\&.GetHashCode ()"

.PP
The default hash function\&. 
.PP
\fBReturns\fP
.RS 4
A hash code for the current \fBQueryVal\fP\&.
.RE
.PP

.PP
Definition at line \fB66\fP of file \fBQueryVal\&.cs\fP\&.
.SS "static bool Fauna\&.QueryVal\&.operator!= (\fBQueryVal\fP left, \fBQueryVal\fP right)\fR [static]\fP"

.PP
Determines whether two specified instances of \fBQueryVal\fP are not equal\&. 
.PP
\fBParameters\fP
.RS 4
\fIleft\fP The first \fBQueryVal\fP to compare\&.
.br
\fIright\fP The second \fBQueryVal\fP to compare\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if left and right are not equal; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB111\fP of file \fBQueryVal\&.cs\fP\&.
.SS "static bool Fauna\&.QueryVal\&.operator== (\fBQueryVal\fP left, \fBQueryVal\fP right)\fR [static]\fP"

.PP
Determines whether two specified instances of \fBQueryVal\fP are equal\&. 
.PP
\fBParameters\fP
.RS 4
\fIleft\fP The first \fBQueryVal\fP to compare\&.
.br
\fIright\fP The second \fBQueryVal\fP to compare\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if left and right are equal; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB90\fP of file \fBQueryVal\&.cs\fP\&.
.SS "override void Fauna\&.QueryVal\&.Serialize (\fBMappingContext\fP ctx, \fBUtf8FaunaWriter\fP writer)"

.PP
Serializes the query value\&. 
.PP
\fBParameters\fP
.RS 4
\fIctx\fP The serialization context\&.
.br
\fIwriter\fP The writer to serialize the query value to\&.
.RE
.PP

.PP
Implements \fBFauna\&.IQueryFragment\fP\&.
.PP
Definition at line \fB31\fP of file \fBQueryVal\&.cs\fP\&.
.SS "override string Fauna\&.QueryVal\&.ToString ()"

.PP
Returns a string that represents the current \fBQueryVal\fP\&. 
.PP
\fBReturns\fP
.RS 4
A string that represents the current \fBQueryVal\fP\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "object? Fauna\&.QueryVal\&.Unwrap\fR [get]\fP"

.PP
Gets the value of the specified type represented in the query\&. 
.PP
Definition at line \fB14\fP of file \fBQueryVal\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
