.TH "Fauna.Core.QueryResponse" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Core.QueryResponse \- Represents the response from a query executed\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBFauna\&.Core\&.QueryFailure\fP, and \fBFauna\&.Core\&.QuerySuccess< T >\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static ? \fBQueryResponse\fP \fBGetFromResponseBody< T >\fP (\fBMappingContext\fP ctx, \fBISerializer\fP< T > serializer, HttpStatusCode statusCode, string body)"
.br
.RI "Asynchronously parses the HTTP response message to create a \fBQueryResponse\fP instance\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "JsonElement \fBRawJson\fP\fR [get]\fP"
.br
.ti -1c
.RI "long \fBLastSeenTxn\fP\fR [get]\fP"
.br
.RI "Gets the last transaction seen by this query\&. "
.ti -1c
.RI "long \fBSchemaVersion\fP\fR [get]\fP"
.br
.RI "Gets the schema version\&. "
.ti -1c
.RI "string \fBSummary\fP = ''\fR [get]\fP"
.br
.RI "Gets a summary of the query execution\&. "
.ti -1c
.RI "Dictionary< string, string > \fBQueryTags\fP = new()\fR [get]\fP"
.br
.RI "Gets a dictionary of query tags, providing additional context about the query\&. "
.ti -1c
.RI "\fBQueryStats\fP \fBStats\fP\fR [get]\fP"
.br
.RI "Gets the statistics related to the query execution\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents the response from a query executed\&. 
.PP
Definition at line \fB13\fP of file \fBQueryResponse\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static ? \fBQueryResponse\fP Fauna\&.Core\&.QueryResponse\&.GetFromResponseBody< T > (\fBMappingContext\fP ctx, \fBISerializer\fP< T > serializer, HttpStatusCode statusCode, string body)\fR [static]\fP"

.PP
Asynchronously parses the HTTP response message to create a \fBQueryResponse\fP instance\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The expected data type of the query response\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIctx\fP \fBSerialization\fP context for handling response data\&.
.br
\fIserializer\fP A serializer for the success data type\&.
.br
\fIstatusCode\fP The HTTP status code\&.
.br
\fIbody\fP The response body\&.
.RE
.PP
\fBReturns\fP
.RS 4
A Task that resolves to a \fBQueryResponse\fP instance\&.
.RE
.PP

.PP
Definition at line \fB93\fP of file \fBQueryResponse\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "long Fauna\&.Core\&.QueryResponse\&.LastSeenTxn\fR [get]\fP"

.PP
Gets the last transaction seen by this query\&. 
.PP
Definition at line \fB20\fP of file \fBQueryResponse\&.cs\fP\&.
.SS "Dictionary<string, string> Fauna\&.Core\&.QueryResponse\&.QueryTags = new()\fR [get]\fP"

.PP
Gets a dictionary of query tags, providing additional context about the query\&. 
.PP
Definition at line \fB35\fP of file \fBQueryResponse\&.cs\fP\&.
.SS "JsonElement Fauna\&.Core\&.QueryResponse\&.RawJson\fR [get]\fP"

.PP
Definition at line \fB15\fP of file \fBQueryResponse\&.cs\fP\&.
.SS "long Fauna\&.Core\&.QueryResponse\&.SchemaVersion\fR [get]\fP"

.PP
Gets the schema version\&. 
.PP
Definition at line \fB25\fP of file \fBQueryResponse\&.cs\fP\&.
.SS "\fBQueryStats\fP Fauna\&.Core\&.QueryResponse\&.Stats\fR [get]\fP"

.PP
Gets the statistics related to the query execution\&. 
.PP
Definition at line \fB40\fP of file \fBQueryResponse\&.cs\fP\&.
.SS "string Fauna\&.Core\&.QueryResponse\&.Summary = ''\fR [get]\fP"

.PP
Gets a summary of the query execution\&. 
.PP
Definition at line \fB30\fP of file \fBQueryResponse\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
