.TH "Fauna.Linq.DataContext.FunctionCall< T >" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Linq.DataContext.FunctionCall< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctionCall\fP (string name, \fBDataContext\fP ctx)"
.br
.ti -1c
.RI "T \fBCall\fP ()"
.br
.ti -1c
.RI "T \fBCall\fP (object a1)"
.br
.ti -1c
.RI "T \fBCall\fP (object a1, object a2)"
.br
.ti -1c
.RI "T \fBCall\fP (object a1, object a2, object a3)"
.br
.ti -1c
.RI "T \fBCall\fP (object[] args)"
.br
.ti -1c
.RI "async Task< T > \fBCallAsync\fP ()"
.br
.ti -1c
.RI "async Task< T > \fBCallAsync\fP (object a1)"
.br
.ti -1c
.RI "async Task< T > \fBCallAsync\fP (object a1, object a2)"
.br
.ti -1c
.RI "async Task< T > \fBCallAsync\fP (object a1, object a2, object a3)"
.br
.ti -1c
.RI "async Task< T > \fBCallAsync\fP (object[] args)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fIT\fP : \fInotnull\fP
.PP
Definition at line \fB166\fP of file \fBDataContext\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBFauna\&.Linq\&.DataContext\&.FunctionCall\fP< T >\&.\fBFunctionCall\fP (string name, \fBDataContext\fP ctx)"

.PP
Definition at line \fB172\fP of file \fBDataContext\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "T \fBFauna\&.Linq\&.DataContext\&.FunctionCall\fP< T >\&.Call ()"

.SS "T \fBFauna\&.Linq\&.DataContext\&.FunctionCall\fP< T >\&.Call (object a1)"

.SS "T \fBFauna\&.Linq\&.DataContext\&.FunctionCall\fP< T >\&.Call (object a1, object a2)"

.SS "T \fBFauna\&.Linq\&.DataContext\&.FunctionCall\fP< T >\&.Call (object a1, object a2, object a3)"

.SS "T \fBFauna\&.Linq\&.DataContext\&.FunctionCall\fP< T >\&.Call (object[] args)"

.SS "async Task< T > \fBFauna\&.Linq\&.DataContext\&.FunctionCall\fP< T >\&.CallAsync ()"

.SS "async Task< T > \fBFauna\&.Linq\&.DataContext\&.FunctionCall\fP< T >\&.CallAsync (object a1)"

.SS "async Task< T > \fBFauna\&.Linq\&.DataContext\&.FunctionCall\fP< T >\&.CallAsync (object a1, object a2)"

.SS "async Task< T > \fBFauna\&.Linq\&.DataContext\&.FunctionCall\fP< T >\&.CallAsync (object a1, object a2, object a3)"

.SS "async Task< T > \fBFauna\&.Linq\&.DataContext\&.FunctionCall\fP< T >\&.CallAsync (object[] args)"

.PP
Definition at line \fB196\fP of file \fBDataContext\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string \fBFauna\&.Linq\&.DataContext\&.FunctionCall\fP< T >\&.Name\fR [get]\fP"

.PP
Definition at line \fB169\fP of file \fBDataContext\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
