.TH "Fauna.Types.Event< T >" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Types.Event< T >
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBEvent\fP< T > \fBFrom\fP (string body, \fBMappingContext\fP ctx)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBEventType\fP \fBType\fP\fR [get]\fP"
.br
.ti -1c
.RI "long \fBTxnTime\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBCursor\fP = null!\fR [get]\fP"
.br
.ti -1c
.RI "T? \fBData\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBQueryStats\fP \fBStats\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fIT\fP : \fInotnull\fP
.PP
Definition at line \fB19\fP of file \fBEvent\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "static \fBEvent\fP< T > \fBFauna\&.Types\&.Event\fP< T >\&.From (string body, \fBMappingContext\fP ctx)\fR [static]\fP"

.PP
Definition at line \fB27\fP of file \fBEvent\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string \fBFauna\&.Types\&.Event\fP< T >\&.Cursor = null!\fR [get]\fP"

.PP
Definition at line \fB23\fP of file \fBEvent\&.cs\fP\&.
.SS "T? \fBFauna\&.Types\&.Event\fP< T >\&.Data\fR [get]\fP"

.PP
Definition at line \fB24\fP of file \fBEvent\&.cs\fP\&.
.SS "\fBQueryStats\fP \fBFauna\&.Types\&.Event\fP< T >\&.\fBStats\fP\fR [get]\fP"

.PP
Definition at line \fB25\fP of file \fBEvent\&.cs\fP\&.
.SS "long \fBFauna\&.Types\&.Event\fP< T >\&.TxnTime\fR [get]\fP"

.PP
Definition at line \fB22\fP of file \fBEvent\&.cs\fP\&.
.SS "\fBEventType\fP \fBFauna\&.Types\&.Event\fP< T >\&.Type\fR [get]\fP"

.PP
Definition at line \fB21\fP of file \fBEvent\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
