.TH "Fauna.QueryExpr" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.QueryExpr \- Represents an FQL query expression\&. This class encapsulates a list of \fBIQueryFragment\fP instances, allowing for complex query constructions\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFauna\&.Query\fP, and \fBFauna\&.IQueryFragment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQueryExpr\fP (IList< \fBIQueryFragment\fP > fragments)"
.br
.RI "Initializes a new instance of the \fBQueryExpr\fP class with a collection of query fragments\&. "
.ti -1c
.RI "\fBQueryExpr\fP (params \fBIQueryFragment\fP[] fragments)"
.br
.RI "Initializes a new instance of the \fBQueryExpr\fP class with one or more query fragments\&. "
.ti -1c
.RI "override void \fBSerialize\fP (\fBMappingContext\fP ctx, \fBUtf8FaunaWriter\fP writer)"
.br
.RI "Serializes the query expression\&. "
.ti -1c
.RI "override bool \fBEquals\fP (\fBQuery\fP? o)"
.br
.RI "Determines whether the specified \fBQueryExpr\fP is equal to the current \fBQueryExpr\fP\&. "
.ti -1c
.RI "override bool \fBEquals\fP (object? o)"
.br
.RI "Determines whether the specified object is equal to the current \fBQueryExpr\fP\&. "
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.RI "The default hash function\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a string that represents the current \fBQueryExpr\fP\&. "
.in -1c

Public Member Functions inherited from \fBFauna\&.Query\fP
.in +1c
.ti -1c
.RI "void \fBSerialize\fP (\fBMappingContext\fP ctx, \fBUtf8FaunaWriter\fP writer)"
.br
.RI "Serializes the query into the provided stream\&. "
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.RI "Returns a hash code for the current query\&. "
.ti -1c
.RI "override bool \fBEquals\fP (object? otherObject)"
.br
.RI "Determines whether the specified object is equal to the current query\&. "
.ti -1c
.RI "bool \fBEquals\fP (\fBQuery\fP? otherQuery)"
.br
.RI "Determines whether the specified \fBQuery\fP is equal to the current query\&. "
.in -1c

Public Member Functions inherited from \fBFauna\&.IQueryFragment\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBoperator==\fP (\fBQueryExpr\fP left, \fBQueryExpr\fP right)"
.br
.RI "Determines whether two specified instances of \fBQueryExpr\fP are equal\&. "
.ti -1c
.RI "static bool \fBoperator!=\fP (\fBQueryExpr\fP left, \fBQueryExpr\fP right)"
.br
.RI "Determines whether two specified instances of \fBQueryExpr\fP are not equal\&. "
.in -1c

Static Public Member Functions inherited from \fBFauna\&.Query\fP
.in +1c
.ti -1c
.RI "static \fBQuery\fP \fBFQL\fP (ref \fBQueryStringHandler\fP handler)"
.br
.RI "Constructs an FQL query using the specified \fBQueryStringHandler\fP\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IReadOnlyCollection< \fBIQueryFragment\fP > \fBUnwrap\fP\fR [get]\fP"
.br
.RI "Gets the readonly collection of query fragments\&. "
.ti -1c
.RI "IReadOnlyCollection< \fBIQueryFragment\fP > \fBFragments\fP\fR [get]\fP"
.br
.RI "Gets the readonly collection of query fragments\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents an FQL query expression\&. This class encapsulates a list of \fBIQueryFragment\fP instances, allowing for complex query constructions\&. 
.PP
Definition at line \fB10\fP of file \fBQueryExpr\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fauna\&.QueryExpr\&.QueryExpr (IList< \fBIQueryFragment\fP > fragments)"

.PP
Initializes a new instance of the \fBQueryExpr\fP class with a collection of query fragments\&. 
.PP
\fBParameters\fP
.RS 4
\fIfragments\fP The collection of \fBIQueryFragment\fP instances\&.
.RE
.PP

.PP
Definition at line \fB16\fP of file \fBQueryExpr\&.cs\fP\&.
.SS "Fauna\&.QueryExpr\&.QueryExpr (params \fBIQueryFragment\fP[] fragments)"

.PP
Initializes a new instance of the \fBQueryExpr\fP class with one or more query fragments\&. 
.PP
\fBParameters\fP
.RS 4
\fIfragments\fP The array of \fBIQueryFragment\fP instances\&.
.RE
.PP

.PP
Definition at line \fB25\fP of file \fBQueryExpr\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool Fauna\&.QueryExpr\&.Equals (object? o)"

.PP
Determines whether the specified object is equal to the current \fBQueryExpr\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIo\fP The object to compare with the current \fBQueryExpr\fP\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if the specified object is equal to the current \fBQueryExpr\fP; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB70\fP of file \fBQueryExpr\&.cs\fP\&.
.SS "override bool Fauna\&.QueryExpr\&.Equals (\fBQuery\fP? o)"

.PP
Determines whether the specified \fBQueryExpr\fP is equal to the current \fBQueryExpr\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIo\fP The \fBQueryExpr\fP to compare with the current \fBQueryExpr\fP\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if the specified \fBQueryExpr\fP is equal to the current \fBQueryExpr\fP; otherwise, false\&.
.RE
.PP

.SS "override int Fauna\&.QueryExpr\&.GetHashCode ()"

.PP
The default hash function\&. 
.PP
\fBReturns\fP
.RS 4
A hash code for the current \fBQueryExpr\fP\&.
.RE
.PP

.SS "static bool Fauna\&.QueryExpr\&.operator!= (\fBQueryExpr\fP left, \fBQueryExpr\fP right)\fR [static]\fP"

.PP
Determines whether two specified instances of \fBQueryExpr\fP are not equal\&. 
.PP
\fBParameters\fP
.RS 4
\fIleft\fP The first \fBQueryExpr\fP to compare\&.
.br
\fIright\fP The second \fBQueryExpr\fP to compare\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if left and right are not equal; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB134\fP of file \fBQueryExpr\&.cs\fP\&.
.SS "static bool Fauna\&.QueryExpr\&.operator== (\fBQueryExpr\fP left, \fBQueryExpr\fP right)\fR [static]\fP"

.PP
Determines whether two specified instances of \fBQueryExpr\fP are equal\&. 
.PP
\fBParameters\fP
.RS 4
\fIleft\fP The first \fBQueryExpr\fP to compare\&.
.br
\fIright\fP The second \fBQueryExpr\fP to compare\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if left and right are equal; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB113\fP of file \fBQueryExpr\&.cs\fP\&.
.SS "override void Fauna\&.QueryExpr\&.Serialize (\fBMappingContext\fP ctx, \fBUtf8FaunaWriter\fP writer)"

.PP
Serializes the query expression\&. 
.PP
\fBParameters\fP
.RS 4
\fIctx\fP The serialization context\&.
.br
\fIwriter\fP The writer to serialize the query expression to\&.
.RE
.PP

.PP
Implements \fBFauna\&.IQueryFragment\fP\&.
.PP
Definition at line \fB45\fP of file \fBQueryExpr\&.cs\fP\&.
.SS "override string Fauna\&.QueryExpr\&.ToString ()"

.PP
Returns a string that represents the current \fBQueryExpr\fP\&. 
.PP
\fBReturns\fP
.RS 4
A string that represents the current \fBQueryExpr\fP\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "IReadOnlyCollection<\fBIQueryFragment\fP> Fauna\&.QueryExpr\&.Fragments\fR [get]\fP"

.PP
Gets the readonly collection of query fragments\&. 
.PP
Definition at line \fB38\fP of file \fBQueryExpr\&.cs\fP\&.
.SS "IReadOnlyCollection<\fBIQueryFragment\fP> Fauna\&.QueryExpr\&.Unwrap\fR [get]\fP"

.PP
Gets the readonly collection of query fragments\&. 
.PP
Definition at line \fB33\fP of file \fBQueryExpr\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
