.TH "Fauna.Types" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Types
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseRef\fP"
.br
.ti -1c
.RI "class \fBBaseRefBuilder\fP"
.br
.ti -1c
.RI "class \fBEvent\fP"
.br
.ti -1c
.RI "class \fBModule\fP"
.br
.RI "Represents a module, a singleton object grouping related functionalities\&. Modules are serialized as @mod values in tagged formats, organizing and encapsulating specific functionalities\&. "
.ti -1c
.RI "class \fBNamedRef\fP"
.br
.RI "Represents a document ref that has a 'name' instead of an 'id'\&. For example, a Role document reference is represented as a \fBNamedRef\fP\&. "
.ti -1c
.RI "class \fBRef\fP"
.br
.RI "Represents a document ref\&. "
.ti -1c
.RI "class \fBStream\fP"
.br
.RI "Represents a \fBFauna\fP stream token\&. "
.ti -1c
.RI "class \fBUnloadedRefException\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEventType\fP { \fBAdd\fP, \fBUpdate\fP, \fBRemove\fP, \fBStatus\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "record \fBPage< T >\fP (IReadOnlyList< T > Data, string? After)"
.br
.RI "Represents a page in a dataset for pagination\&. "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBFauna\&.Types\&.EventType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIAdd \fP
.TP
\f(BIUpdate \fP
.TP
\f(BIRemove \fP
.TP
\f(BIStatus \fP
.PP
Definition at line \fB11\fP of file \fBEvent\&.cs\fP\&.
.SH "Function Documentation"
.PP 
.SS "record Fauna\&.Types\&.Page< T > (IReadOnlyList< T > Data, string? After)"

.PP
Represents a page in a dataset for pagination\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIT\fP The type of data contained in the page\&.
.RE
.PP
\fBParameters\fP
.RS 4
\fIData\fP The IReadOnlyList<T> of data items on the page\&.
.br
\fIAfter\fP The cursor for the next page, if available\&.
.RE
.PP

.PP
Used for segmenting large datasets into pages with cursors to navigate between them\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
