.TH "Fauna.Types.Stream" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Types.Stream \- Represents a \fBFauna\fP stream token\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IEquatable< Stream >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStream\fP (string token)"
.br
.ti -1c
.RI "void \fBSerialize\fP (System\&.IO\&.Stream stream)"
.br
.ti -1c
.RI "bool \fBEquals\fP (\fBStream\fP? other)"
.br
.RI "Determines whether the specified \fBStream\fP is equal to the current \fBStream\fP\&. "
.ti -1c
.RI "override bool \fBEquals\fP (object? obj)"
.br
.RI "Determines whether the specified object is equal to the current \fBStream\fP\&. "
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.RI "The default hash function\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "long? \fBStartTs\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBLastCursor\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a \fBFauna\fP stream token\&. 
.PP
Definition at line \fB8\fP of file \fBStream\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fauna\&.Types\&.Stream\&.Stream (string token)"

.PP
Definition at line \fB10\fP of file \fBStream\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool Fauna\&.Types\&.Stream\&.Equals (object? obj)"

.PP
Determines whether the specified object is equal to the current \fBStream\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIobj\fP The object to compare with the current \fBStream\fP\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if the specified object is equal to the current \fBStream\fP; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB59\fP of file \fBStream\&.cs\fP\&.
.SS "bool Fauna\&.Types\&.Stream\&.Equals (\fBStream\fP? other)"

.PP
Determines whether the specified \fBStream\fP is equal to the current \fBStream\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP The \fBStream\fP to compare with the current \fBStream\fP\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if the specified \fBStream\fP is equal to the current \fBStream\fP; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB47\fP of file \fBStream\&.cs\fP\&.
.SS "override int Fauna\&.Types\&.Stream\&.GetHashCode ()"

.PP
The default hash function\&. 
.PP
\fBReturns\fP
.RS 4
A hash code for the current \fBStream\fP\&.
.RE
.PP

.PP
Definition at line \fB71\fP of file \fBStream\&.cs\fP\&.
.SS "void Fauna\&.Types\&.Stream\&.Serialize (System\&.IO\&.Stream stream)"

.PP
Definition at line \fB24\fP of file \fBStream\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string? Fauna\&.Types\&.Stream\&.LastCursor\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB22\fP of file \fBStream\&.cs\fP\&.
.SS "long? Fauna\&.Types\&.Stream\&.StartTs\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB20\fP of file \fBStream\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
