.TH "Fauna.Mapping.FieldAttribute" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Mapping.FieldAttribute \- Attribute used to specify fields on a \fBFauna\fP document or struct\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFauna\&.Mapping\&.BaseFieldAttribute\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFieldAttribute\fP ()"
.br
.ti -1c
.RI "\fBFieldAttribute\fP (string name)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBFauna\&.Mapping\&.BaseFieldAttribute\fP
.in +1c
.ti -1c
.RI "readonly? string \fBName\fP"
.br
.ti -1c
.RI "\fBFieldType\fP \fBType\fP"
.br
.in -1c

Protected Member Functions inherited from \fBFauna\&.Mapping\&.BaseFieldAttribute\fP
.in +1c
.ti -1c
.RI "\fBBaseFieldAttribute\fP (string? name, \fBFieldType\fP type)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Attribute used to specify fields on a \fBFauna\fP document or struct\&. 
.PP
Definition at line \fB39\fP of file \fBAttributes\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fauna\&.Mapping\&.FieldAttribute\&.FieldAttribute ()"

.PP
Definition at line \fB41\fP of file \fBAttributes\&.cs\fP\&.
.SS "Fauna\&.Mapping\&.FieldAttribute\&.FieldAttribute (string name)"

.PP
Definition at line \fB42\fP of file \fBAttributes\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
