.TH "Fauna.Linq.DataContext.Collection< Doc >.IndexCall" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Linq.DataContext.Collection< Doc >.IndexCall
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIndexCall\fP (\fBICollection\fP coll, string name, \fBDataContext\fP ctx)"
.br
.ti -1c
.RI "\fBIndex\fP< Doc > \fBCall\fP ()"
.br
.ti -1c
.RI "\fBIndex\fP< Doc > \fBCall\fP (object a1)"
.br
.ti -1c
.RI "\fBIndex\fP< Doc > \fBCall\fP (object a1, object a2)"
.br
.ti -1c
.RI "\fBIndex\fP< Doc > \fBCall\fP (object a1, object a2, object a3)"
.br
.ti -1c
.RI "\fBIndex\fP< Doc > \fBCall\fP (object[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB107\fP of file \fBDataContext\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBFauna\&.Linq\&.DataContext\&.Collection\fP< Doc >\&.IndexCall\&.IndexCall (\fBICollection\fP coll, string name, \fBDataContext\fP ctx)"

.PP
Definition at line \fB113\fP of file \fBDataContext\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIndex\fP< Doc > \fBFauna\&.Linq\&.DataContext\&.Collection\fP< Doc >\&.IndexCall\&.Call ()"

.SS "\fBIndex\fP< Doc > \fBFauna\&.Linq\&.DataContext\&.Collection\fP< Doc >\&.IndexCall\&.Call (object a1)"

.SS "\fBIndex\fP< Doc > \fBFauna\&.Linq\&.DataContext\&.Collection\fP< Doc >\&.IndexCall\&.Call (object a1, object a2)"

.SS "\fBIndex\fP< Doc > \fBFauna\&.Linq\&.DataContext\&.Collection\fP< Doc >\&.IndexCall\&.Call (object a1, object a2, object a3)"

.SS "\fBIndex\fP< Doc > \fBFauna\&.Linq\&.DataContext\&.Collection\fP< Doc >\&.IndexCall\&.Call (object[] args)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
