.TH "Fauna.Exceptions.IRetryableException" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Exceptions.IRetryableException \- Represents an interface for exceptions that are potentially recoverable through retrying the failed operation\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBFauna\&.Exceptions\&.ContendedTransactionException\fP, and \fBFauna\&.Exceptions\&.ThrottlingException\fP\&.
.SH "Detailed Description"
.PP 
Represents an interface for exceptions that are potentially recoverable through retrying the failed operation\&. 
.PP
Definition at line \fB6\fP of file \fBIRetryableException\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
