.TH "Fauna.Exceptions.SerializationException" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Exceptions.SerializationException \- Represents error that occur during serialization and deserialization of \fBFauna\fP data\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerializationException\fP (string? message)"
.br
.ti -1c
.RI "\fBSerializationException\fP (string? message, Exception? innerException)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents error that occur during serialization and deserialization of \fBFauna\fP data\&. 
.PP
Definition at line \fB6\fP of file \fBSerializationException\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fauna\&.Exceptions\&.SerializationException\&.SerializationException (string? message)"

.PP
Definition at line \fB8\fP of file \fBSerializationException\&.cs\fP\&.
.SS "Fauna\&.Exceptions\&.SerializationException\&.SerializationException (string? message, Exception? innerException)"

.PP
Definition at line \fB12\fP of file \fBSerializationException\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
