.TH "Fauna.QueryStringHandler" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.QueryStringHandler \- Provides a mechanism to build FQL query expressions using interpolated strings\&. This structure collects fragments and literals to construct complex query expressions\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQueryStringHandler\fP (int literalLength, int formattedCount)"
.br
.RI "Initializes a new instance of the \fBQueryStringHandler\fP struct\&. "
.ti -1c
.RI "void \fBAppendLiteral\fP (string value)"
.br
.RI "Appends a literal string to the query\&. "
.ti -1c
.RI "void \fBAppendFormatted\fP (object? value)"
.br
.RI "Appends a formatted value to the query\&. The value is wrapped as a \fBQueryVal\fP or \fBQueryExpr\fP depending on its type\&. "
.ti -1c
.RI "\fBQuery\fP \fBResult\fP ()"
.br
.RI "Constructs and returns a \fBQuery\fP instance representing the current state of the handler\&. "
.in -1c
.SH "Detailed Description"
.PP 
Provides a mechanism to build FQL query expressions using interpolated strings\&. This structure collects fragments and literals to construct complex query expressions\&. 
.PP
Definition at line \fB9\fP of file \fBQueryStringHandler\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fauna\&.QueryStringHandler\&.QueryStringHandler (int literalLength, int formattedCount)"

.PP
Initializes a new instance of the \fBQueryStringHandler\fP struct\&. 
.PP
\fBParameters\fP
.RS 4
\fIliteralLength\fP The estimated length of the literals in the interpolated string\&.
.br
\fIformattedCount\fP The number of format items in the interpolated string\&.
.RE
.PP

.PP
Definition at line \fB18\fP of file \fBQueryStringHandler\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Fauna\&.QueryStringHandler\&.AppendFormatted (object? value)"

.PP
Appends a formatted value to the query\&. The value is wrapped as a \fBQueryVal\fP or \fBQueryExpr\fP depending on its type\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The value to append\&.
.RE
.PP

.PP
Definition at line \fB36\fP of file \fBQueryStringHandler\&.cs\fP\&.
.SS "void Fauna\&.QueryStringHandler\&.AppendLiteral (string value)"

.PP
Appends a literal string to the query\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The literal string to append\&.
.RE
.PP

.PP
Definition at line \fB27\fP of file \fBQueryStringHandler\&.cs\fP\&.
.SS "\fBQuery\fP Fauna\&.QueryStringHandler\&.Result ()"

.PP
Constructs and returns a \fBQuery\fP instance representing the current state of the handler\&. 
.PP
\fBReturns\fP
.RS 4
A \fBQuery\fP instance representing the constructed query fragments\&.
.RE
.PP

.PP
Definition at line \fB52\fP of file \fBQueryStringHandler\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
