.TH "Fauna.Core.ErrorInfo" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Core.ErrorInfo \- Contains detailed information about an error in a query response\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string? \fBCode\fP\fR [get]\fP"
.br
.RI "The error code when a query fails\&. "
.ti -1c
.RI "string? \fBMessage\fP\fR [get]\fP"
.br
.RI "The detailed message describing the cause of the error\&. "
.ti -1c
.RI "\fBConstraintFailure\fP[] \fBConstraintFailures\fP\fR [get]\fP"
.br
.RI "The constraint failures that occurred during the query\&. "
.ti -1c
.RI "object? \fBAbort\fP\fR [get]\fP"
.br
.RI "The information about an abort operation within a transaction\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains detailed information about an error in a query response\&. 
.PP
Definition at line \fB10\fP of file \fBErrorInfo\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "object? Fauna\&.Core\&.ErrorInfo\&.Abort\fR [get]\fP"

.PP
The information about an abort operation within a transaction\&. 
.PP
Definition at line \fB34\fP of file \fBErrorInfo\&.cs\fP\&.
.SS "string? Fauna\&.Core\&.ErrorInfo\&.Code\fR [get]\fP"

.PP
The error code when a query fails\&. 
.PP
Definition at line \fB16\fP of file \fBErrorInfo\&.cs\fP\&.
.SS "\fBConstraintFailure\fP [] Fauna\&.Core\&.ErrorInfo\&.ConstraintFailures\fR [get]\fP"

.PP
The constraint failures that occurred during the query\&. 
.PP
Definition at line \fB28\fP of file \fBErrorInfo\&.cs\fP\&.
.SS "string? Fauna\&.Core\&.ErrorInfo\&.Message\fR [get]\fP"

.PP
The detailed message describing the cause of the error\&. 
.PP
Definition at line \fB22\fP of file \fBErrorInfo\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
