.TH "Fauna.Client" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Client \- Represents a client for interacting with a \fBFauna\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFauna\&.BaseClient\fP, and IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClient\fP ()"
.br
.RI "Initializes a new instance of a \fBClient\fP with the default configuration\&. Assumes the environment variable FAUNA_SECRET is set\&. "
.ti -1c
.RI "\fBClient\fP (string secret)"
.br
.RI "Initializes a new instance of a \fBClient\fP with a secret\&. "
.ti -1c
.RI "\fBClient\fP (\fBConfiguration\fP config)"
.br
.RI "Initializes a new instance of the \fBClient\fP with a custom \fBConfiguration\fP\&. "
.ti -1c
.RI "DB \fBDataContext< DB >\fP ()"
.br
.RI "Create and return a new database context which uses the \fBClient\fP instance\&. "
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "Disposes the resources used by the \fBClient\fP class\&. "
.in -1c

Public Member Functions inherited from \fBFauna\&.BaseClient\fP
.in +1c
.ti -1c
.RI "Task< \fBQuerySuccess\fP< T > > \fBQueryAsync< T >\fP (\fBQuery\fP query, \fBQueryOptions\fP? queryOptions=null, CancellationToken cancel=default)"
.br
.RI "Asynchronously executes a specified FQL query against the \fBFauna\fP database and returns the typed result\&. "
.ti -1c
.RI "Task< \fBQuerySuccess\fP< object?> > \fBQueryAsync\fP (\fBQuery\fP query, \fBQueryOptions\fP? queryOptions=null, CancellationToken cancel=default)"
.br
.RI "Asynchronously executes a specified FQL query against the \fBFauna\fP database\&. "
.ti -1c
.RI "Task< \fBQuerySuccess\fP< T > > \fBQueryAsync< T >\fP (\fBQuery\fP query, \fBISerializer\fP< T > serializer, \fBQueryOptions\fP? queryOptions=null, CancellationToken cancel=default)"
.br
.RI "Asynchronously executes a specified FQL query against the \fBFauna\fP database and returns the typed result\&. "
.ti -1c
.RI "Task< \fBQuerySuccess\fP< object?> > \fBQueryAsync\fP (\fBQuery\fP query, \fBISerializer\fP serializer, \fBQueryOptions\fP? queryOptions=null, CancellationToken cancel=default)"
.br
.RI "Asynchronously executes a specified FQL query against the \fBFauna\fP database and returns the typed result\&. "
.ti -1c
.RI "IAsyncEnumerable< Page< T > > \fBPaginateAsync< T >\fP (\fBQuery\fP query, \fBQueryOptions\fP? queryOptions=null, CancellationToken cancel=default)"
.br
.RI "Asynchronously iterates over pages of a \fBFauna\fP query result, automatically fetching subsequent pages using the 'after' cursor\&. "
.ti -1c
.RI "IAsyncEnumerable< Page< T > > \fBPaginateAsync< T >\fP (Page< T > page, \fBQueryOptions\fP? queryOptions=null, CancellationToken cancel=default)"
.br
.RI "Asynchronously iterates over pages of a \fBFauna\fP query result, automatically fetching subsequent pages using the 'after' cursor\&. The provided page is the first page yielded\&. "
.ti -1c
.RI "IAsyncEnumerable< Page< object?> > \fBPaginateAsync\fP (\fBQuery\fP query, \fBQueryOptions\fP? queryOptions=null, CancellationToken cancel=default)"
.br
.RI "Asynchronously iterates over pages of a \fBFauna\fP query result, automatically fetching subsequent pages using the 'after' cursor\&. "
.ti -1c
.RI "IAsyncEnumerable< Page< object?> > \fBPaginateAsync\fP (Page< object?> page, \fBQueryOptions\fP? queryOptions=null, CancellationToken cancel=default)"
.br
.RI "Asynchronously iterates over pages of a \fBFauna\fP query result, automatically fetching subsequent pages using the 'after' cursor\&. The provided page is the first page yielded\&. "
.ti -1c
.RI "IAsyncEnumerable< Page< T > > \fBPaginateAsync< T >\fP (\fBQuery\fP query, \fBISerializer\fP< T > elemSerializer, \fBQueryOptions\fP? queryOptions=null, CancellationToken cancel=default)"
.br
.RI "Asynchronously iterates over pages of a \fBFauna\fP query result, automatically fetching subsequent pages using the 'after' cursor\&. "
.ti -1c
.RI "IAsyncEnumerable< Page< T > > \fBPaginateAsync< T >\fP (Page< T > page, \fBISerializer\fP< T > elemSerializer, \fBQueryOptions\fP? queryOptions=null, CancellationToken cancel=default)"
.br
.RI "Asynchronously iterates over pages of a \fBFauna\fP query result, automatically fetching subsequent pages using the 'after' cursor\&. The provided page is the first page yielded\&. "
.ti -1c
.RI "IAsyncEnumerable< Page< object?> > \fBPaginateAsync\fP (\fBQuery\fP query, \fBISerializer\fP elemSerializer, \fBQueryOptions\fP? queryOptions=null, CancellationToken cancel=default)"
.br
.RI "Asynchronously iterates over pages of a \fBFauna\fP query result, automatically fetching subsequent pages using the 'after' cursor\&. "
.ti -1c
.RI "IAsyncEnumerable< Page< object?> > \fBPaginateAsync\fP (Page< object?> page, \fBISerializer\fP elemSerializer, \fBQueryOptions\fP? queryOptions=null, CancellationToken cancel=default)"
.br
.RI "Asynchronously iterates over pages of a \fBFauna\fP query result, automatically fetching subsequent pages using the 'after' cursor\&. The provided page is the first page yielded\&. "
.ti -1c
.RI "async Task< T > \fBLoadRefAsync< T >\fP (\fBBaseRef\fP< T > reference, CancellationToken cancel=default)"
.br
.RI "Asynchronously executes a specified FQL query against the \fBFauna\fP database and returns the typed result\&. "
.ti -1c
.RI "async Task< \fBStreamEnumerable\fP< T > > \fBEventStreamAsync< T >\fP (\fBQuery\fP query, \fBQueryOptions\fP? queryOptions=null, \fBStreamOptions\fP? streamOptions=null, CancellationToken cancellationToken=default)"
.br
.RI "Retrieves a Stream token from \fBFauna\fP and returns a StreamEnumerable for the stream events\&. "
.ti -1c
.RI "IAsyncEnumerator< \fBEvent\fP< T > > \fBSubscribeStream< T >\fP (\fBStream\fP stream, \fBMappingContext\fP ctx, CancellationToken cancel=default)"
.br
.RI "Opens the stream with \fBFauna\fP and returns an enumerator for the stream events\&. "
.in -1c

Public Member Functions inherited from \fBFauna\&.IClient\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly? \fBIStatsCollector\fP \fBStatsCollector\fP"
.br
.RI "Provides collection and aggregation of query statistics\&. Can be set to null in the \fBConfiguration\fP\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "long \fBLastSeenTxn\fP\fR [get]\fP"
.br
.RI "Gets the timestamp of the last transaction seen by this client\&. "
.in -1c

Properties inherited from \fBFauna\&.BaseClient\fP
.SH "Detailed Description"
.PP 
Represents a client for interacting with a \fBFauna\fP\&. 
.PP
Definition at line \fB15\fP of file \fBClient\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fauna\&.Client\&.Client ()"

.PP
Initializes a new instance of a \fBClient\fP with the default configuration\&. Assumes the environment variable FAUNA_SECRET is set\&. 
.PP
Definition at line \fB44\fP of file \fBClient\&.cs\fP\&.
.SS "Fauna\&.Client\&.Client (string secret)"

.PP
Initializes a new instance of a \fBClient\fP with a secret\&. 
.PP
\fBParameters\fP
.RS 4
\fIsecret\fP The secret key for authentication\&.
.RE
.PP

.PP
Definition at line \fB50\fP of file \fBClient\&.cs\fP\&.
.SS "Fauna\&.Client\&.Client (\fBConfiguration\fP config)"

.PP
Initializes a new instance of the \fBClient\fP with a custom \fBConfiguration\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIconfig\fP The configuration settings for the client\&.
.RE
.PP

.PP
Definition at line \fB59\fP of file \fBClient\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "DB Fauna\&.Client\&.DataContext< DB > ()"

.PP
Create and return a new database context which uses the \fBClient\fP instance\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIDB\fP The DataContext subtype to instantiate\&.
.RE
.PP
\fBReturns\fP
.RS 4
An instance of \fIDB\fP \&.
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fIDB\fP : \fIDataContext\fP
.PP
Definition at line \fB71\fP of file \fBClient\&.cs\fP\&.
.SS "void Fauna\&.Client\&.Dispose ()"

.PP
Disposes the resources used by the \fBClient\fP class\&. 
.PP
Definition at line \fB91\fP of file \fBClient\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly? \fBIStatsCollector\fP Fauna\&.Client\&.StatsCollector"

.PP
Provides collection and aggregation of query statistics\&. Can be set to null in the \fBConfiguration\fP\&. 
.PP
Definition at line \fB33\fP of file \fBClient\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "long Fauna\&.Client\&.LastSeenTxn\fR [get]\fP"

.PP
Gets the timestamp of the last transaction seen by this client\&. 
.PP
Definition at line \fB38\fP of file \fBClient\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
