.TH "Fauna.Serialization" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Serialization
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseRefSerializer\fP"
.br
.ti -1c
.RI "class \fBBaseSerializer\fP"
.br
.ti -1c
.RI "class \fBBooleanSerializer\fP"
.br
.ti -1c
.RI "class \fBByteSerializer\fP"
.br
.ti -1c
.RI "class \fBClassSerializer\fP"
.br
.ti -1c
.RI "class \fBDateOnlySerializer\fP"
.br
.ti -1c
.RI "class \fBDateTimeOffsetSerializer\fP"
.br
.ti -1c
.RI "class \fBDateTimeSerializer\fP"
.br
.ti -1c
.RI "class \fBDictionarySerializer\fP"
.br
.ti -1c
.RI "class \fBDoubleSerializer\fP"
.br
.ti -1c
.RI "class \fBDynamicSerializer\fP"
.br
.ti -1c
.RI "class \fBFloatSerializer\fP"
.br
.ti -1c
.RI "class \fBIntSerializer\fP"
.br
.ti -1c
.RI "interface \fBIPartialDocumentSerializer\fP"
.br
.ti -1c
.RI "interface \fBISerializer\fP"
.br
.ti -1c
.RI "class \fBListSerializer\fP"
.br
.ti -1c
.RI "class \fBLongSerializer\fP"
.br
.ti -1c
.RI "class \fBModuleSerializer\fP"
.br
.ti -1c
.RI "class \fBNamedRefSerializer\fP"
.br
.ti -1c
.RI "class \fBNullableSerializer\fP"
.br
.ti -1c
.RI "class \fBNullableStructSerializer\fP"
.br
.ti -1c
.RI "class \fBPageSerializer\fP"
.br
.ti -1c
.RI "class \fBQueryArrSerializer\fP"
.br
.ti -1c
.RI "class \fBQueryExprSerializer\fP"
.br
.ti -1c
.RI "class \fBQueryLiteralSerializer\fP"
.br
.ti -1c
.RI "class \fBQueryObjSerializer\fP"
.br
.ti -1c
.RI "class \fBQuerySerializer\fP"
.br
.ti -1c
.RI "class \fBQueryValSerializer\fP"
.br
.ti -1c
.RI "class \fBRefSerializer\fP"
.br
.ti -1c
.RI "class \fBSByteSerializer\fP"
.br
.ti -1c
.RI "class \fBSerializer\fP"
.br
.RI "Represents methods for serializing objects to and from \fBFauna\fP's value format\&. "
.ti -1c
.RI "class \fBShortSerializer\fP"
.br
.ti -1c
.RI "class \fBStreamSerializer\fP"
.br
.ti -1c
.RI "class \fBStringSerializer\fP"
.br
.ti -1c
.RI "class \fBUIntSerializer\fP"
.br
.ti -1c
.RI "class \fBUShortSerializer\fP"
.br
.ti -1c
.RI "struct \fBUtf8FaunaReader\fP"
.br
.RI "Represents a reader that provides fast, non-cached, forward-only access to serialized data\&. "
.ti -1c
.RI "class \fBUtf8FaunaWriter\fP"
.br
.RI "Provides functionality for writing data in a streaming manner to a buffer or a stream\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTokenType\fP { \fBNone\fP, \fBStartObject\fP, \fBEndObject\fP, \fBStartArray\fP, \fBEndArray\fP, \fBStartPage\fP, \fBEndPage\fP, \fBStartRef\fP, \fBEndRef\fP, \fBStartDocument\fP, \fBEndDocument\fP, \fBFieldName\fP, \fBString\fP, \fBInt\fP, \fBLong\fP, \fBDouble\fP, \fBDate\fP, \fBTime\fP, \fBTrue\fP, \fBFalse\fP, \fBNull\fP, \fBModule\fP, \fBStream\fP }"
.br
.RI "Enumerates the types of tokens used in \fBFauna\fP serialization\&. "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBFauna\&.Serialization\&.TokenType\fP"

.PP
Enumerates the types of tokens used in \fBFauna\fP serialization\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINone \fP
There is no value\&. This is the default token type if no data has been read by the T:Fauna\&.Serialization\&.Utf8FaunaReader\&. 
.TP
\f(BIStartObject \fP
The token type is the start of a \fBFauna\fP object\&. 
.TP
\f(BIEndObject \fP
The token type is the end of a \fBFauna\fP object\&. 
.TP
\f(BIStartArray \fP
The token type is the start of a \fBFauna\fP array\&. 
.TP
\f(BIEndArray \fP
The token type is the end of a \fBFauna\fP array\&. 
.TP
\f(BIStartPage \fP
The token type is the start of a \fBFauna\fP set (a\&.k\&.a\&. page)\&. 
.TP
\f(BIEndPage \fP
The token type is the end of a \fBFauna\fP set (a\&.k\&.a\&. page)\&. 
.TP
\f(BIStartRef \fP
The token type is the start of a \fBFauna\fP ref\&. 
.TP
\f(BIEndRef \fP
The token type is the end of a \fBFauna\fP ref\&. 
.TP
\f(BIStartDocument \fP
The token type is the start of a \fBFauna\fP document\&. 
.TP
\f(BIEndDocument \fP
The token type is the end of a \fBFauna\fP document\&. 
.TP
\f(BIFieldName \fP
The token type is a \fBFauna\fP property name\&. 
.TP
\f(BIString \fP
The token type is a \fBFauna\fP string\&. 
.TP
\f(BIInt \fP
The token type is a \fBFauna\fP integer\&. 
.TP
\f(BILong \fP
The token type is a \fBFauna\fP long\&. 
.TP
\f(BIDouble \fP
The token type is a \fBFauna\fP double\&. 
.TP
\f(BIDate \fP
The token type is a \fBFauna\fP date\&. 
.TP
\f(BITime \fP
The token type is a \fBFauna\fP time\&. 
.TP
\f(BITrue \fP
The token type is the \fBFauna\fP literal true\&. 
.TP
\f(BIFalse \fP
The token type is the \fBFauna\fP literal false\&. 
.TP
\f(BINull \fP
The token type is the \fBFauna\fP literal null\&. 
.TP
\f(BIModule \fP
The token type is the \fBFauna\fP module\&. 
.TP
\f(BIStream \fP
The token type is the \fBFauna\fP stream token\&. 
.PP
Definition at line \fB6\fP of file \fBTokenType\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
