.TH "Fauna.Serialization.Utf8FaunaReader" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Serialization.Utf8FaunaReader \- Represents a reader that provides fast, non-cached, forward-only access to serialized data\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUtf8FaunaReader\fP (ReadOnlySequence< byte > bytes)"
.br
.RI "Initializes a new \fBUtf8FaunaReader\fP to read from a ReadOnlySequence of bytes\&. "
.ti -1c
.RI "\fBUtf8FaunaReader\fP (string str)"
.br
.RI "Initializes a new \fBUtf8FaunaReader\fP to read from a string\&. "
.ti -1c
.RI "void \fBSkip\fP ()"
.br
.RI "Skips the value of the current token\&. "
.ti -1c
.RI "bool \fBRead\fP ()"
.br
.RI "Reads the next token from the source\&. "
.ti -1c
.RI "object? \fBGetValue\fP ()"
.br
.RI "Gets the value of the current token\&. "
.ti -1c
.RI "string? \fBGetString\fP ()"
.br
.RI "Retrieves a string value from the current token\&. "
.ti -1c
.RI "bool \fBGetBoolean\fP ()"
.br
.RI "Retrieves a boolean value from the current JSON token\&. "
.ti -1c
.RI "DateOnly \fBGetDate\fP ()"
.br
.RI "Retrieves a DateOnly value from the current token\&. "
.ti -1c
.RI "float \fBGetFloat\fP ()"
.br
.RI "Retrieves a float value from the current token\&. "
.ti -1c
.RI "double \fBGetDouble\fP ()"
.br
.RI "Retrieves a double value from the current token\&. "
.ti -1c
.RI "decimal \fBGetDoubleAsDecimal\fP ()"
.br
.RI "Retrieves a decimal value from the current token\&. "
.ti -1c
.RI "byte \fBGetByte\fP ()"
.br
.RI "Retrieves an byte value from the current token\&. "
.ti -1c
.RI "byte[] \fBGetBytes\fP ()"
.br
.RI "Retrieves a byte array value from the current token\&. "
.ti -1c
.RI "sbyte \fBGetUnsignedByte\fP ()"
.br
.RI "Retrieves an unsigned byte value from the current token\&. "
.ti -1c
.RI "int \fBGetInt\fP ()"
.br
.RI "Retrieves an integer value from the current token\&. "
.ti -1c
.RI "uint \fBGetUnsignedInt\fP ()"
.br
.RI "Retrieves an unsigned integer value from the current token\&. "
.ti -1c
.RI "short \fBGetShort\fP ()"
.br
.RI "Retrieves an short value from the current token\&. "
.ti -1c
.RI "ushort \fBGetUnsignedShort\fP ()"
.br
.RI "Retrieves an unsigned short value from the current token\&. "
.ti -1c
.RI "long \fBGetLong\fP ()"
.br
.RI "Retrieves a long value from the current token\&. "
.ti -1c
.RI "\fBModule\fP \fBGetModule\fP ()"
.br
.RI "Retrieves a Module object from the current token\&. "
.ti -1c
.RI "\fBStream\fP \fBGetStream\fP ()"
.br
.RI "Retrieves a Stream token string from the current token\&. "
.ti -1c
.RI "DateTime \fBGetTime\fP ()"
.br
.RI "Retrieves a DateTime value from the current token\&. "
.ti -1c
.RI "string \fBTryGetString\fP (out string value)"
.br
.RI "Tries to retrieve a string value from the current token\&. "
.ti -1c
.RI "bool \fBTryGetBoolean\fP (out bool value)"
.br
.RI "Tries to retrieve a boolean value from the current token\&. "
.ti -1c
.RI "DateTime \fBTryGetDateTime\fP (out DateTime value)"
.br
.RI "Tries to retrieve a DateTime value from the current token\&. "
.ti -1c
.RI "double \fBTryGetDouble\fP (out double value)"
.br
.RI "Tries to retrieve a double value from the current token\&. "
.ti -1c
.RI "int \fBTryGetInt\fP (out int value)"
.br
.RI "Tries to retrieve an integer value from the current token\&. "
.ti -1c
.RI "long \fBTryGetLong\fP (out long value)"
.br
.RI "Tries to retrieve a long value from the current token\&. "
.ti -1c
.RI "\fBModule\fP \fBTryGetModule\fP (out \fBModule\fP value)"
.br
.RI "Tries to retrieve a Module object from the current token\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTokenType\fP \fBCurrentTokenType\fP\fR [get]\fP"
.br
.RI "Gets the type of the current token\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a reader that provides fast, non-cached, forward-only access to serialized data\&. 
.PP
Definition at line \fB14\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fauna\&.Serialization\&.Utf8FaunaReader\&.Utf8FaunaReader (ReadOnlySequence< byte > bytes)"

.PP
Initializes a new \fBUtf8FaunaReader\fP to read from a ReadOnlySequence of bytes\&. 
.PP
\fBParameters\fP
.RS 4
\fIbytes\fP The sequence of bytes to read from\&.
.RE
.PP

.PP
Definition at line \fB46\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "Fauna\&.Serialization\&.Utf8FaunaReader\&.Utf8FaunaReader (string str)"

.PP
Initializes a new \fBUtf8FaunaReader\fP to read from a string\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP The string to read from\&.
.RE
.PP

.PP
Definition at line \fB56\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool Fauna\&.Serialization\&.Utf8FaunaReader\&.GetBoolean ()"

.PP
Retrieves a boolean value from the current JSON token\&. 
.PP
\fBReturns\fP
.RS 4
A boolean representation of the current token's value\&.
.RE
.PP

.PP
Definition at line \fB203\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "byte Fauna\&.Serialization\&.Utf8FaunaReader\&.GetByte ()"

.PP
Retrieves an byte value from the current token\&. 
.PP
\fBReturns\fP
.RS 4
A byte representation of the current token's value\&.
.RE
.PP

.PP
Definition at line \fB291\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "byte[] Fauna\&.Serialization\&.Utf8FaunaReader\&.GetBytes ()"

.PP
Retrieves a byte array value from the current token\&. 
.PP
\fBReturns\fP
.RS 4
A byte array representation of the current token's value\&.
.RE
.PP

.PP
Definition at line \fB309\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "DateOnly Fauna\&.Serialization\&.Utf8FaunaReader\&.GetDate ()"

.PP
Retrieves a DateOnly value from the current token\&. 
.PP
\fBReturns\fP
.RS 4
A DateOnly representation of the current token's value\&.
.RE
.PP

.PP
Definition at line \fB219\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "double Fauna\&.Serialization\&.Utf8FaunaReader\&.GetDouble ()"

.PP
Retrieves a double value from the current token\&. 
.PP
\fBReturns\fP
.RS 4
A double representation of the current token's value\&.
.RE
.PP

.PP
Definition at line \fB255\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "decimal Fauna\&.Serialization\&.Utf8FaunaReader\&.GetDoubleAsDecimal ()"

.PP
Retrieves a decimal value from the current token\&. 
.PP
\fBReturns\fP
.RS 4
A decimal representation of the current token's value\&.
.RE
.PP

.PP
Definition at line \fB273\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "float Fauna\&.Serialization\&.Utf8FaunaReader\&.GetFloat ()"

.PP
Retrieves a float value from the current token\&. 
.PP
\fBReturns\fP
.RS 4
A float representation of the current token's value\&.
.RE
.PP

.PP
Definition at line \fB237\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "int Fauna\&.Serialization\&.Utf8FaunaReader\&.GetInt ()"

.PP
Retrieves an integer value from the current token\&. 
.PP
\fBReturns\fP
.RS 4
An integer representation of the current token's value\&.
.RE
.PP

.PP
Definition at line \fB345\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "long Fauna\&.Serialization\&.Utf8FaunaReader\&.GetLong ()"

.PP
Retrieves a long value from the current token\&. 
.PP
\fBReturns\fP
.RS 4
A long representation of the current token's value\&.
.RE
.PP

.PP
Definition at line \fB415\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "\fBModule\fP Fauna\&.Serialization\&.Utf8FaunaReader\&.GetModule ()"

.PP
Retrieves a Module object from the current token\&. 
.PP
\fBReturns\fP
.RS 4
A Module representation of the current token's value\&.
.RE
.PP

.PP
Definition at line \fB433\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "short Fauna\&.Serialization\&.Utf8FaunaReader\&.GetShort ()"

.PP
Retrieves an short value from the current token\&. 
.PP
\fBReturns\fP
.RS 4
An short representation of the current token's value\&.
.RE
.PP

.PP
Definition at line \fB381\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "\fBStream\fP Fauna\&.Serialization\&.Utf8FaunaReader\&.GetStream ()"

.PP
Retrieves a Stream token string from the current token\&. 
.PP
\fBReturns\fP
.RS 4
A Stream token string of the current token's value\&.
.RE
.PP

.PP
Definition at line \fB444\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "string? Fauna\&.Serialization\&.Utf8FaunaReader\&.GetString ()"

.PP
Retrieves a string value from the current token\&. 
.PP
\fBReturns\fP
.RS 4
A string representation of the current token's value\&.
.RE
.PP

.PP
Definition at line \fB182\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "DateTime Fauna\&.Serialization\&.Utf8FaunaReader\&.GetTime ()"

.PP
Retrieves a DateTime value from the current token\&. 
.PP
\fBReturns\fP
.RS 4
A DateTime representation of the current token's value\&.
.RE
.PP

.PP
Definition at line \fB455\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "sbyte Fauna\&.Serialization\&.Utf8FaunaReader\&.GetUnsignedByte ()"

.PP
Retrieves an unsigned byte value from the current token\&. 
.PP
\fBReturns\fP
.RS 4
An unsigned byte representation of the current token's value\&.
.RE
.PP

.PP
Definition at line \fB327\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "uint Fauna\&.Serialization\&.Utf8FaunaReader\&.GetUnsignedInt ()"

.PP
Retrieves an unsigned integer value from the current token\&. 
.PP
\fBReturns\fP
.RS 4
An unsigned integer representation of the current token's value\&.
.RE
.PP

.PP
Definition at line \fB363\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "ushort Fauna\&.Serialization\&.Utf8FaunaReader\&.GetUnsignedShort ()"

.PP
Retrieves an unsigned short value from the current token\&. 
.PP
\fBReturns\fP
.RS 4
An unsigned short representation of the current token's value\&.
.RE
.PP

.PP
Definition at line \fB398\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "object? Fauna\&.Serialization\&.Utf8FaunaReader\&.GetValue ()"

.PP
Gets the value of the current token\&. 
.PP
\fBReturns\fP
.RS 4
The value of the current token, or null if no value is associated with the token\&.
.RE
.PP
\fBExceptions\fP
.RS 4
\fISerializationException\fP Thrown when an error occurs during token value retrieval\&.
.RE
.PP

.PP
Definition at line \fB161\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "bool Fauna\&.Serialization\&.Utf8FaunaReader\&.Read ()"

.PP
Reads the next token from the source\&. 
.PP
\fBReturns\fP
.RS 4
true if the token was read successfully; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB94\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "void Fauna\&.Serialization\&.Utf8FaunaReader\&.Skip ()"

.PP
Skips the value of the current token\&. 
.PP
Definition at line \fB67\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "bool Fauna\&.Serialization\&.Utf8FaunaReader\&.TryGetBoolean (out bool value)"

.PP
Tries to retrieve a boolean value from the current token\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP When this method returns, contains the boolean value, if the conversion succeeded, or false if the conversion failed\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if the token's value could be converted to a boolean; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB484\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "DateTime Fauna\&.Serialization\&.Utf8FaunaReader\&.TryGetDateTime (out DateTime value)"

.PP
Tries to retrieve a DateTime value from the current token\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP When this method returns, contains the DateTime value, if the conversion succeeded, or the default DateTime value if the conversion failed\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if the token's value could be converted to a DateTime; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB494\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "double Fauna\&.Serialization\&.Utf8FaunaReader\&.TryGetDouble (out double value)"

.PP
Tries to retrieve a double value from the current token\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP When this method returns, contains the double value, if the conversion succeeded, or 0\&.0 if the conversion failed\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if the token's value could be converted to a double; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB504\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "int Fauna\&.Serialization\&.Utf8FaunaReader\&.TryGetInt (out int value)"

.PP
Tries to retrieve an integer value from the current token\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP When this method returns, contains the integer value, if the conversion succeeded, or 0 if the conversion failed\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if the token's value could be converted to an integer; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB514\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "long Fauna\&.Serialization\&.Utf8FaunaReader\&.TryGetLong (out long value)"

.PP
Tries to retrieve a long value from the current token\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP When this method returns, contains the long value, if the conversion succeeded, or 0 if the conversion failed\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if the token's value could be converted to a long; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB524\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "\fBModule\fP Fauna\&.Serialization\&.Utf8FaunaReader\&.TryGetModule (out \fBModule\fP value)"

.PP
Tries to retrieve a Module object from the current token\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP When this method returns, contains the Module object, if the conversion succeeded, or null if the conversion failed\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if the token's value could be converted to a Module; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB534\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SS "string Fauna\&.Serialization\&.Utf8FaunaReader\&.TryGetString (out string value)"

.PP
Tries to retrieve a string value from the current token\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP When this method returns, contains the string value, if the conversion succeeded, or null if the conversion failed\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if the token's value could be converted to a string; otherwise, false\&.
.RE
.PP

.PP
Definition at line \fB474\fP of file \fBUtf8FaunaReader\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBTokenType\fP Fauna\&.Serialization\&.Utf8FaunaReader\&.CurrentTokenType\fR [get]\fP"

.PP
Gets the type of the current token\&. 
.PP
Definition at line \fB34\fP of file \fBUtf8FaunaReader\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
