.TH "Fauna.Core.StreamEnumerable< T >" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Core.StreamEnumerable< T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async IAsyncEnumerator< \fBEvent\fP< T > > \fBGetAsyncEnumerator\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBToken\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBType Constraints\fP
.TP
\fIT\fP : \fInotnull\fP
.PP
Definition at line \fB6\fP of file \fBStreamEnumerable\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "async IAsyncEnumerator< \fBEvent\fP< T > > \fBFauna\&.Core\&.StreamEnumerable\fP< T >\&.GetAsyncEnumerator ()"

.PP
Definition at line \fB24\fP of file \fBStreamEnumerable\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string \fBFauna\&.Core\&.StreamEnumerable\fP< T >\&.Token\fR [get]\fP"

.PP
Definition at line \fB12\fP of file \fBStreamEnumerable\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
