.TH "Fauna.Linq" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Linq
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDataContext\fP"
.br
.ti -1c
.RI "class \fBDataContextBuilder\fP"
.br
.ti -1c
.RI "class \fBIntermediateQueryHelpers\fP"
.br
.ti -1c
.RI "interface \fBIPipelineExecutor\fP"
.br
.ti -1c
.RI "interface \fBIQuerySource\fP"
.br
.ti -1c
.RI "class \fBMappedDeserializer\fP"
.br
.ti -1c
.RI "class \fBProjectionAnalysisVisitor\fP"
.br
.ti -1c
.RI "class \fBProjectionDeserializer\fP"
.br
.ti -1c
.RI "class \fBProjectionRewriteVisitor\fP"
.br
.ti -1c
.RI "class \fBQuerySource\fP"
.br
.ti -1c
.RI "class \fBQuerySourceExtensions\fP"
.br
.ti -1c
.RI "class \fBSubQuerySwitch\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPipelineMode\fP { \fBQuery\fP, \fBProject\fP, \fBSetLoad\fP, \fBScalar\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBFauna\&.Linq\&.PipelineMode\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIQuery \fP
.TP
\f(BIProject \fP
.TP
\f(BISetLoad \fP
.TP
\f(BIScalar \fP
.PP
Definition at line \fB6\fP of file \fBPipeline\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
