.TH "Fauna.Core" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Core
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConnection\fP"
.br
.RI "A class that handles HTTP requests and retries\&. "
.ti -1c
.RI "class \fBEndpoints\fP"
.br
.RI "Represents the endpoints used for accessing \fBFauna\fP\&. "
.ti -1c
.RI "struct \fBErrorInfo\fP"
.br
.RI "Contains detailed information about an error in a query response\&. "
.ti -1c
.RI "struct \fBHeaders\fP"
.br
.RI "Contains constant values for HTTP header names used in \fBFauna\fP API requests\&. "
.ti -1c
.RI "interface \fBIConnection\fP"
.br
.RI "Represents an interface for making HTTP requests\&. "
.ti -1c
.RI "interface \fBIStatsCollector\fP"
.br
.ti -1c
.RI "class \fBQueryFailure\fP"
.br
.RI "Represents a failed query response\&. "
.ti -1c
.RI "class \fBQueryOptions\fP"
.br
.RI "Represents the options for customizing \fBFauna\fP queries\&. "
.ti -1c
.RI "class \fBQueryResponse\fP"
.br
.RI "Represents the response from a query executed\&. "
.ti -1c
.RI "struct \fBQueryStats\fP"
.br
.RI "Contains statistics related to the execution of a query in the \fBFauna\fP database\&. "
.ti -1c
.RI "class \fBQuerySuccess\fP"
.br
.RI "Represents a successful query response\&. "
.ti -1c
.RI "struct \fBResponseFields\fP"
.br
.RI "Contains constant values for the response field names returned by \fBFauna\fP API queries\&. "
.ti -1c
.RI "class \fBRetryConfiguration\fP"
.br
.RI "A class representing a retry configuration for queries\&. "
.ti -1c
.RI "struct \fBStats\fP"
.br
.ti -1c
.RI "class \fBStatsCollector\fP"
.br
.ti -1c
.RI "class \fBStreamEnumerable\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
