.TH "Fauna.Exceptions.NetworkException" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Exceptions.NetworkException \- Represents an exception that occurs when a request fails due to a network issue\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBFauna\&.Exceptions\&.FaunaException\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNetworkException\fP (string message, HttpStatusCode statusCode, string body)"
.br
.in -1c

Public Member Functions inherited from \fBFauna\&.Exceptions\&.FaunaException\fP
.in +1c
.ti -1c
.RI "\fBFaunaException\fP ()"
.br
.ti -1c
.RI "\fBFaunaException\fP (string message)"
.br
.ti -1c
.RI "\fBFaunaException\fP (string message, Exception innerException)"
.br
.ti -1c
.RI "\fBFaunaException\fP (\fBErrorInfo\fP err)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBResponseBody\fP\fR [get]\fP"
.br
.ti -1c
.RI "HttpStatusCode \fBStatusCode\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents an exception that occurs when a request fails due to a network issue\&. 
.PP
Definition at line \fB8\fP of file \fBNetworkException\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Fauna\&.Exceptions\&.NetworkException\&.NetworkException (string message, HttpStatusCode statusCode, string body)"

.PP
Definition at line \fB14\fP of file \fBNetworkException\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Fauna\&.Exceptions\&.NetworkException\&.ResponseBody\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBNetworkException\&.cs\fP\&.
.SS "HttpStatusCode Fauna\&.Exceptions\&.NetworkException\&.StatusCode\fR [get]\fP"

.PP
Definition at line \fB12\fP of file \fBNetworkException\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
