.TH "Fauna.Serialization.ISerializer< out T >" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Serialization.ISerializer< out T >
.SH SYNOPSIS
.br
.PP
.PP
Inherits ISerializer\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "new T \fBDeserialize\fP (\fBMappingContext\fP context, ref \fBUtf8FaunaReader\fP reader)"
.br
.ti -1c
.RI "object? \fBDeserialize\fP (\fBMappingContext\fP context, ref \fBUtf8FaunaReader\fP reader)"
.br
.ti -1c
.RI "void \fBSerialize\fP (\fBMappingContext\fP ctx, \fBUtf8FaunaWriter\fP w, object? o)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBISerializer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "new T \fBFauna\&.Serialization\&.ISerializer\fP< out T >\&.Deserialize (\fBMappingContext\fP context, ref \fBUtf8FaunaReader\fP reader)"

.SS "object? \fBFauna\&.Serialization\&.ISerializer\fP< out T >\&.Deserialize (\fBMappingContext\fP context, ref \fBUtf8FaunaReader\fP reader)"

.SS "void \fBFauna\&.Serialization\&.ISerializer\fP< out T >\&.Serialize (\fBMappingContext\fP ctx, \fBUtf8FaunaWriter\fP w, object? o)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
