.TH "Fauna.Core.IStatsCollector" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Core.IStatsCollector
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBFauna\&.Core\&.StatsCollector\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAdd\fP (\fBQueryStats\fP stats)"
.br
.RI "Add the \fBQueryStats\fP to the current counts\&. "
.ti -1c
.RI "\fBStats\fP \fBRead\fP ()"
.br
.RI "Return the collected \fBStats\fP\&. "
.ti -1c
.RI "\fBStats\fP \fBReadAndReset\fP ()"
.br
.RI "Return the collected \fBStats\fP and Reset counts\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBStatsCollector\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Fauna\&.Core\&.IStatsCollector\&.Add (\fBQueryStats\fP stats)"

.PP
Add the \fBQueryStats\fP to the current counts\&. 
.PP
\fBParameters\fP
.RS 4
\fIstats\fP \fBQueryStats\fP
.RE
.PP

.PP
Implemented in \fBFauna\&.Core\&.StatsCollector\fP\&.
.SS "\fBStats\fP Fauna\&.Core\&.IStatsCollector\&.Read ()"

.PP
Return the collected \fBStats\fP\&. 
.PP
Implemented in \fBFauna\&.Core\&.StatsCollector\fP\&.
.SS "\fBStats\fP Fauna\&.Core\&.IStatsCollector\&.ReadAndReset ()"

.PP
Return the collected \fBStats\fP and Reset counts\&. 
.PP
Implemented in \fBFauna\&.Core\&.StatsCollector\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
