.TH "Fauna.Core.QueryStats" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Core.QueryStats \- Contains statistics related to the execution of a query in the \fBFauna\fP database\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a string representation of the query statistics\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBComputeOps\fP\fR [get]\fP"
.br
.RI "The number of compute operations consumed by the query\&. "
.ti -1c
.RI "int \fBReadOps\fP\fR [get]\fP"
.br
.RI "The number of read operations consumed by the query\&. "
.ti -1c
.RI "int \fBWriteOps\fP\fR [get]\fP"
.br
.RI "The number of write operations consumed by the query\&. "
.ti -1c
.RI "int \fBQueryTimeMs\fP\fR [get]\fP"
.br
.RI "The query processing time in milliseconds\&. "
.ti -1c
.RI "int \fBContentionRetries\fP\fR [get]\fP"
.br
.RI "The write contention retry count\&. "
.ti -1c
.RI "int \fBStorageBytesRead\fP\fR [get]\fP"
.br
.RI "The amount of data read from storage, in bytes\&. "
.ti -1c
.RI "int \fBStorageBytesWrite\fP\fR [get]\fP"
.br
.RI "The amount of data written to storage, in bytes\&. "
.ti -1c
.RI "List< string > \fBRateLimitsHit\fP\fR [get]\fP"
.br
.RI "The types of operations that were limited or approaching rate limits\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains statistics related to the execution of a query in the \fBFauna\fP database\&. 
.PP
Definition at line \fB9\fP of file \fBQueryStats\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override string Fauna\&.Core\&.QueryStats\&.ToString ()"

.PP
Returns a string representation of the query statistics\&. 
.PP
\fBReturns\fP
.RS 4
A string detailing the query execution statistics\&.
.RE
.PP

.PP
Definition at line \fB63\fP of file \fBQueryStats\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Fauna\&.Core\&.QueryStats\&.ComputeOps\fR [get]\fP"

.PP
The number of compute operations consumed by the query\&. 
.PP
Definition at line \fB15\fP of file \fBQueryStats\&.cs\fP\&.
.SS "int Fauna\&.Core\&.QueryStats\&.ContentionRetries\fR [get]\fP"

.PP
The write contention retry count\&. 
.PP
Definition at line \fB39\fP of file \fBQueryStats\&.cs\fP\&.
.SS "int Fauna\&.Core\&.QueryStats\&.QueryTimeMs\fR [get]\fP"

.PP
The query processing time in milliseconds\&. 
.PP
Definition at line \fB33\fP of file \fBQueryStats\&.cs\fP\&.
.SS "List<string> Fauna\&.Core\&.QueryStats\&.RateLimitsHit\fR [get]\fP"

.PP
The types of operations that were limited or approaching rate limits\&. 
.PP
Definition at line \fB57\fP of file \fBQueryStats\&.cs\fP\&.
.SS "int Fauna\&.Core\&.QueryStats\&.ReadOps\fR [get]\fP"

.PP
The number of read operations consumed by the query\&. 
.PP
Definition at line \fB21\fP of file \fBQueryStats\&.cs\fP\&.
.SS "int Fauna\&.Core\&.QueryStats\&.StorageBytesRead\fR [get]\fP"

.PP
The amount of data read from storage, in bytes\&. 
.PP
Definition at line \fB45\fP of file \fBQueryStats\&.cs\fP\&.
.SS "int Fauna\&.Core\&.QueryStats\&.StorageBytesWrite\fR [get]\fP"

.PP
The amount of data written to storage, in bytes\&. 
.PP
Definition at line \fB51\fP of file \fBQueryStats\&.cs\fP\&.
.SS "int Fauna\&.Core\&.QueryStats\&.WriteOps\fR [get]\fP"

.PP
The number of write operations consumed by the query\&. 
.PP
Definition at line \fB27\fP of file \fBQueryStats\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
