.TH "Fauna.Mapping.FieldInfo" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna.Mapping.FieldInfo \- A class that encapsulates the field mapping, serialization, and deserialization of a particular field in \fBFauna\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fR [get]\fP"
.br
.RI "The name of the field\&. "
.ti -1c
.RI "PropertyInfo \fBProperty\fP\fR [get]\fP"
.br
.RI "The property info of an associated class\&. "
.ti -1c
.RI "\fBFieldType\fP \fBFieldType\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBType\fP\fR [get]\fP"
.br
.RI "The \fBType\fP that the field should deserialize into\&. "
.ti -1c
.RI "bool \fBIsNullable\fP\fR [get]\fP"
.br
.RI "Whether the field is nullable\&. "
.in -1c
.SH "Detailed Description"
.PP 
A class that encapsulates the field mapping, serialization, and deserialization of a particular field in \fBFauna\fP\&. 
.PP
Definition at line \fB9\fP of file \fBFieldInfo\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBFieldType\fP Fauna\&.Mapping\&.FieldInfo\&.FieldType\fR [get]\fP"

.PP
Definition at line \fB20\fP of file \fBFieldInfo\&.cs\fP\&.
.SS "bool Fauna\&.Mapping\&.FieldInfo\&.IsNullable\fR [get]\fP"

.PP
Whether the field is nullable\&. 
.PP
Definition at line \fB29\fP of file \fBFieldInfo\&.cs\fP\&.
.SS "string Fauna\&.Mapping\&.FieldInfo\&.Name\fR [get]\fP"

.PP
The name of the field\&. 
.PP
Definition at line \fB14\fP of file \fBFieldInfo\&.cs\fP\&.
.SS "PropertyInfo Fauna\&.Mapping\&.FieldInfo\&.Property\fR [get]\fP"

.PP
The property info of an associated class\&. 
.PP
Definition at line \fB18\fP of file \fBFieldInfo\&.cs\fP\&.
.SS "Type Fauna\&.Mapping\&.FieldInfo\&.Type\fR [get]\fP"

.PP
The \fBType\fP that the field should deserialize into\&. 
.PP
Definition at line \fB25\fP of file \fBFieldInfo\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
