.TH "Fauna/Mapping/FieldType.cs" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Mapping/FieldType.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFauna\fP"
.br
.ti -1c
.RI "namespace \fBFauna\&.Mapping\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFauna\&.Mapping\&.FieldType\fP { \fBFauna\&.Mapping\&.ClientGeneratedId\fP, \fBFauna\&.Mapping\&.ServerGeneratedId\fP, \fBFauna\&.Mapping\&.Coll\fP, \fBFauna\&.Mapping\&.Ts\fP, \fBFauna\&.Mapping\&.Field\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
