.TH "Fauna/Query/IQueryFragment.cs" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Query/IQueryFragment.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBFauna\&.IQueryFragment\fP"
.br
.RI "Represents the base interface for a query fragment used for FQL query construction\&. "
.ti -1c
.RI "class \fBFauna\&.IQueryFragmentExtensions\fP"
.br
.RI "Provides extension methods for the \fBIQueryFragment\fP interface to enhance its functionality, allowing for more flexible serialization options\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFauna\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
