.TH "Fauna/Serialization/ListSerializer.cs" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Serialization/ListSerializer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFauna\&.Serialization\&.ListSerializer< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFauna\fP"
.br
.ti -1c
.RI "namespace \fBFauna\&.Serialization\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBArgumentException\fP = System\&.ArgumentException"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBArgumentException\fP = System\&.ArgumentException"

.PP
Definition at line \fB4\fP of file \fBListSerializer\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
