.TH "Fauna/Mapping/MappingInfo.cs" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Mapping/MappingInfo.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFauna\&.Mapping\&.MappingInfo\fP"
.br
.RI "A class that encapsulates the class mapping, serialization, and deserialization of a \fBFauna\fP object, including documents\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFauna\fP"
.br
.ti -1c
.RI "namespace \fBFauna\&.Mapping\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBModule\fP = \fBFauna\&.Types\&.Module\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBModule\fP = \fBFauna\&.Types\&.Module\fP"

.PP
Definition at line \fB4\fP of file \fBMappingInfo\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
