.TH "Fauna/Types/Page.cs" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Types/Page.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFauna\fP"
.br
.ti -1c
.RI "namespace \fBFauna\&.Types\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "record \fBFauna\&.Types\&.Page< T >\fP (IReadOnlyList< T > Data, string? After)"
.br
.RI "Represents a page in a dataset for pagination\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
