.TH "Fauna/Linq/Pipeline.cs" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Linq/Pipeline.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFauna\fP"
.br
.ti -1c
.RI "namespace \fBFauna\&.Linq\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFauna\&.Linq\&.PipelineMode\fP { \fBFauna\&.Linq\&.Query\fP, \fBFauna\&.Linq\&.Project\fP, \fBFauna\&.Linq\&.SetLoad\fP, \fBFauna\&.Linq\&.Scalar\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
