.TH "Fauna/Core/QueryResponse.cs" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Core/QueryResponse.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFauna\&.Core\&.QueryResponse\fP"
.br
.RI "Represents the response from a query executed\&. "
.ti -1c
.RI "class \fBFauna\&.Core\&.QuerySuccess< T >\fP"
.br
.RI "Represents a successful query response\&. "
.ti -1c
.RI "class \fBFauna\&.Core\&.QueryFailure\fP"
.br
.RI "Represents a failed query response\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFauna\fP"
.br
.ti -1c
.RI "namespace \fBFauna\&.Core\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
