.TH "Fauna/Linq/QuerySourceDsl.cs" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Linq/QuerySourceDsl.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFauna\&.Linq\&.QuerySource< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFauna\fP"
.br
.ti -1c
.RI "namespace \fBFauna\&.Linq\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBQH\fP = Fauna\&.Linq\&.IntermediateQueryHelpers"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef Fauna Linq IntermediateQueryHelpers \fBQH\fP = Fauna\&.Linq\&.IntermediateQueryHelpers"

.PP
Definition at line \fB8\fP of file \fBQuerySourceDsl\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
