.TH "Fauna/Core/StatsCollector.cs" 3 "Version 0.4.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Core/StatsCollector.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBFauna\&.Core\&.Stats\fP"
.br
.ti -1c
.RI "interface \fBFauna\&.Core\&.IStatsCollector\fP"
.br
.ti -1c
.RI "class \fBFauna\&.Core\&.StatsCollector\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFauna\fP"
.br
.ti -1c
.RI "namespace \fBFauna\&.Core\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
