.TH "Fauna/Types/Stream.cs" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Types/Stream.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFauna\&.Types\&.Stream\fP"
.br
.RI "Represents a \fBFauna\fP stream token\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFauna\fP"
.br
.ti -1c
.RI "namespace \fBFauna\&.Types\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
