.TH "Fauna/Core/StreamEnumerable.cs" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Core/StreamEnumerable.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFauna\&.Core\&.StreamEnumerable< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFauna\fP"
.br
.ti -1c
.RI "namespace \fBFauna\&.Core\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBStream\fP = \fBFauna\&.Types\&.Stream\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBStream\fP = \fBFauna\&.Types\&.Stream\fP"

.PP
Definition at line \fB2\fP of file \fBStreamEnumerable\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
