.TH "Fauna/Serialization/TokenType.cs" 3 "Version 0.3.0-beta" "Fauna v10 .NET/C# Driver" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Fauna/Serialization/TokenType.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFauna\fP"
.br
.ti -1c
.RI "namespace \fBFauna\&.Serialization\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFauna\&.Serialization\&.TokenType\fP { \fBFauna\&.Serialization\&.None\fP, \fBFauna\&.Serialization\&.StartObject\fP, \fBFauna\&.Serialization\&.EndObject\fP, \fBFauna\&.Serialization\&.StartArray\fP, \fBFauna\&.Serialization\&.EndArray\fP, \fBFauna\&.Serialization\&.StartPage\fP, \fBFauna\&.Serialization\&.EndPage\fP, \fBFauna\&.Serialization\&.StartRef\fP, \fBFauna\&.Serialization\&.EndRef\fP, \fBFauna\&.Serialization\&.StartDocument\fP, \fBFauna\&.Serialization\&.EndDocument\fP, \fBFauna\&.Serialization\&.FieldName\fP, \fBFauna\&.Serialization\&.String\fP, \fBFauna\&.Serialization\&.Int\fP, \fBFauna\&.Serialization\&.Long\fP, \fBFauna\&.Serialization\&.Double\fP, \fBFauna\&.Serialization\&.Date\fP, \fBFauna\&.Serialization\&.Time\fP, \fBFauna\&.Serialization\&.True\fP, \fBFauna\&.Serialization\&.False\fP, \fBFauna\&.Serialization\&.Null\fP, \fBFauna\&.Serialization\&.Module\fP, \fBFauna\&.Serialization\&.Stream\fP }"
.br
.RI "Enumerates the types of tokens used in \fBFauna\fP serialization\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fauna v10 \&.NET/C# Driver from the source code\&.
