var searchData=
[
  ['badgatewayexception_0',['BadGatewayException',['../class_fauna_1_1_exceptions_1_1_bad_gateway_exception.html',1,'Fauna::Exceptions']]],
  ['baseclient_1',['BaseClient',['../class_fauna_1_1_base_client.html',1,'Fauna']]],
  ['basedocument_2',['BaseDocument',['../class_fauna_1_1_types_1_1_base_document.html',1,'Fauna::Types']]],
  ['baseserializer_3',['BaseSerializer',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20bool_20_3e_4',['BaseSerializer&lt; bool &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20byte_20_3e_5',['BaseSerializer&lt; byte &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20dateonly_20_3e_6',['BaseSerializer&lt; DateOnly &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20datetime_20_3e_7',['BaseSerializer&lt; DateTime &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20datetimeoffset_20_3e_8',['BaseSerializer&lt; DateTimeOffset &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20dictionary_3c_20string_2c_20t_20_3e_20_3e_9',['BaseSerializer&lt; Dictionary&lt; string, T &gt; &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20double_20_3e_10',['BaseSerializer&lt; double &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20float_20_3e_11',['BaseSerializer&lt; float &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20int_20_3e_12',['BaseSerializer&lt; int &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20list_3c_20t_20_3e_20_3e_13',['BaseSerializer&lt; List&lt; T &gt; &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20long_20_3e_14',['BaseSerializer&lt; long &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20module_20_3e_15',['BaseSerializer&lt; Module &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20nullabledocument_3c_20t_20_3e_20_3e_16',['BaseSerializer&lt; NullableDocument&lt; T &gt; &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20o_20_3e_17',['BaseSerializer&lt; O &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20object_3f_3e_18',['BaseSerializer&lt; object?&gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20object_3f_5b_5d_3e_19',['BaseSerializer&lt; object?[]&gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20page_3c_20t_20_3e_20_3e_20',['BaseSerializer&lt; Page&lt; T &gt; &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20sbyte_20_3e_21',['BaseSerializer&lt; sbyte &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20short_20_3e_22',['BaseSerializer&lt; short &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20stream_20_3e_23',['BaseSerializer&lt; Stream &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20string_3f_3e_24',['BaseSerializer&lt; string?&gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20t_3f_3e_25',['BaseSerializer&lt; T?&gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20uint_20_3e_26',['BaseSerializer&lt; uint &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20ushort_20_3e_27',['BaseSerializer&lt; ushort &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]]
];
