---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: self-config
    type: git
    icon: github
    source:
      uri: https://github.com/fauna/fauna-dotnet
      branch: main
      paths:
        - concourse/pipeline.yml

  - name: notify
    type: slack-notification
    source:
      url: ((slack-webhook))

  - name: perf-notify
    type: slack-notification
    source:
      # webhook for #notify-driver-perf channel
      url: ((driver-perf-slack-url))

  - name: repo.git
    type: git
    icon: github
    source:
      uri: https://github.com/fauna/fauna-dotnet
      branch: main
      
  - name: docs.git
    type: git
    icon: github
    source:
      uri: git@github.com:fauna/fauna-dotnet.git
      branch: gh-pages
      private_key: ((github-ssh-key))

  - name: dev-tests-trigger
    type: time
    source:
      interval: 6h

jobs:
  - name: set-self
    plan:
      - get: self-config
        trigger: true

      - set_pipeline: self
        file: self-config/concourse/pipeline.yml

  - name: perf-tests-dev
    serial: true
    public: false
    plan:
      - get: dev-tests-trigger
        trigger: true

      - get: repo.git

      - task: run-perf
        file: repo.git/concourse/tasks/perf.yml
        params:
          FAUNA_ENDPOINT: https://db.fauna-dev.com
          FAUNA_SECRET: ((dev-driver-perf-test-key))
          FAUNA_ENVIRONMENT: dev
        on_success:
          put: perf-notify
          params:
            text_file: slack-message/perf-stats

  - name: release
    serial: true
    public: false
    plan:
      - get: repo.git
      - get: docs.git

      - task: publish
        file: repo.git/concourse/tasks/publish.yml
        params:
          NUGET_API_KEY: ((nuget_api_key))
        on_success:
          put: notify
          params:
            text_file: slack-message/publish

      - task: publish-docs
        file: repo.git/concourse/tasks/publish-docs.yml

      - put: docs.git
        params:
          repository: docs-updated.git
