---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: notify
    type: slack-notification
    source:
      url: ((slack-webhook))

  - name: repo.git
    type: git
    icon: github
    source:
      uri: https://github.com/fauna/fauna-dotnet
      branch: main
      private_key: ((github-ssh-key))

jobs:
  - name: release
    serial: true
    public: false
    plan:
      - get: repo.git

      - task: publish
        file: repo.git/concourse/tasks/publish.yml
        params:
          NUGET_API_KEY: ((nuget_api_key))
        on_success:
          put: notify
          params:
            text_file: slack-message/publish
