---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: mcr.microsoft.com/dotnet/sdk
    tag: 8.0-noble

params:
  FAUNA_ENDPOINT:
  FAUNA_SECRET:

inputs:
  - name: repo.git

outputs:
  - name: slack-message

run:
  path: ./repo.git/concourse/scripts/perf.sh
