---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: mcr.microsoft.com/dotnet/sdk
    tag: 8.0-alpine3.19

params:
  NUGET_API_KEY:

inputs:
  - name: repo.git

outputs:
  - name: slack-message

run:
  path: ./repo.git/concourse/scripts/publish.sh