var searchData=
[
  ['badgatewayexception_0',['badgatewayexception',['../class_fauna_1_1_exceptions_1_1_bad_gateway_exception.html#a6970cd0357d02d9cb797f233299ee055',1,'Fauna.Exceptions.BadGatewayException.BadGatewayException()'],['../class_fauna_1_1_exceptions_1_1_bad_gateway_exception.html',1,'Fauna.Exceptions.BadGatewayException']]],
  ['badgatewayexception_2ecs_1',['BadGatewayException.cs',['../_bad_gateway_exception_8cs.html',1,'']]],
  ['baseclient_2',['BaseClient',['../class_fauna_1_1_base_client.html',1,'Fauna']]],
  ['basefieldattribute_3',['BaseFieldAttribute',['../class_fauna_1_1_mapping_1_1_base_field_attribute.html',1,'Fauna::Mapping']]],
  ['baseref_4',['BaseRef',['../class_fauna_1_1_types_1_1_base_ref.html',1,'Fauna::Types']]],
  ['baseref_2ecs_5',['BaseRef.cs',['../_base_ref_8cs.html',1,'']]],
  ['baserefbuilder_2ecs_6',['BaseRefBuilder.cs',['../_base_ref_builder_8cs.html',1,'']]],
  ['baserefserializer_2ecs_7',['BaseRefSerializer.cs',['../_base_ref_serializer_8cs.html',1,'']]],
  ['baseserializer_8',['BaseSerializer',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20baseref_3c_20t_20_3e_20_3e_9',['BaseSerializer&lt; BaseRef&lt; T &gt; &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20bool_20_3e_10',['BaseSerializer&lt; bool &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20byte_20_3e_11',['BaseSerializer&lt; byte &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20byte_5b_5d_3e_12',['BaseSerializer&lt; byte[]&gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20dateonly_20_3e_13',['BaseSerializer&lt; DateOnly &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20datetime_20_3e_14',['BaseSerializer&lt; DateTime &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20datetimeoffset_20_3e_15',['BaseSerializer&lt; DateTimeOffset &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20dictionary_3c_20string_2c_20t_20_3e_20_3e_16',['BaseSerializer&lt; Dictionary&lt; string, T &gt; &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20double_20_3e_17',['BaseSerializer&lt; double &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20eventsource_20_3e_18',['BaseSerializer&lt; EventSource &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20float_20_3e_19',['BaseSerializer&lt; float &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20int_20_3e_20',['BaseSerializer&lt; int &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20list_3c_20t_20_3e_20_3e_21',['BaseSerializer&lt; List&lt; T &gt; &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20long_20_3e_22',['BaseSerializer&lt; long &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20module_20_3e_23',['BaseSerializer&lt; Module &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20namedref_3c_20t_20_3e_20_3e_24',['BaseSerializer&lt; NamedRef&lt; T &gt; &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20o_20_3e_25',['BaseSerializer&lt; O &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20object_3f_3e_26',['BaseSerializer&lt; object?&gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20object_3f_5b_5d_3e_27',['BaseSerializer&lt; object?[]&gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20page_3c_20t_20_3e_20_3e_28',['BaseSerializer&lt; Page&lt; T &gt; &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20query_20_3e_29',['BaseSerializer&lt; Query &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20queryarr_20_3e_30',['BaseSerializer&lt; QueryArr &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20queryexpr_20_3e_31',['BaseSerializer&lt; QueryExpr &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20queryliteral_20_3e_32',['BaseSerializer&lt; QueryLiteral &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20queryobj_20_3e_33',['BaseSerializer&lt; QueryObj &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20ref_3c_20t_20_3e_20_3e_34',['BaseSerializer&lt; Ref&lt; T &gt; &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20sbyte_20_3e_35',['BaseSerializer&lt; sbyte &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20short_20_3e_36',['BaseSerializer&lt; short &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20string_3f_3e_37',['BaseSerializer&lt; string?&gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20t_3f_3e_38',['BaseSerializer&lt; T?&gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20uint_20_3e_39',['BaseSerializer&lt; uint &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['baseserializer_3c_20ushort_20_3e_40',['BaseSerializer&lt; ushort &gt;',['../class_fauna_1_1_serialization_1_1_base_serializer.html',1,'Fauna::Serialization']]],
  ['boolean_41',['Boolean',['../namespace_fauna_1_1_serialization.html#a55a27484b93b289186af1f246b15e4ada27226c864bac7454a8504f8edb15d95b',1,'Fauna::Serialization']]],
  ['bytes_42',['bytes',['../namespace_fauna_1_1_serialization.html#a55a27484b93b289186af1f246b15e4ada600e754f49b68aa0fc90a9cd64eb7051',1,'Fauna.Serialization.Bytes'],['../namespace_fauna_1_1_serialization.html#a564aa46d376b2e193a3c208775e46d50a600e754f49b68aa0fc90a9cd64eb7051',1,'Fauna.Serialization.Bytes']]]
];
