name: Code coverage

on:
  pull_request:
    paths:
      - '**/*.cs'

jobs:
  dotnet-cc:

    runs-on: ubuntu-latest

    services:
      fauna:
        image: fauna/faunadb
        ports:
          - 8443:8443

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Get baseline code coverage
        run: |
          git fetch
          git checkout origin/main
          dotnet test --framework net8.0 --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="$GITHUB_WORKSPACE/cc_results/"
      
      - name: Generate baseline code coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.8
        with:
          reports: "$GITHUB_WORKSPACE/cc_results/coverage.net8.0.opencover.xml"
          targetdir: "$GITHUB_WORKSPACE/report"
          historydir: "$GITHUB_WORKSPACE/history"
          reporttypes: 'JsonSummary'

      - name: Get code coverage with changes
        run: |
          git fetch
          git checkout ${{ github.event.pull_request.head.ref }}
          dotnet test --framework net8.0 --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="$GITHUB_WORKSPACE/cc_results/"
      
      - name: Generate code coverage report with delta
        uses: danielpalme/ReportGenerator-GitHub-Action@5.3.8
        with:
          reports: "$GITHUB_WORKSPACE/cc_results/coverage.net8.0.opencover.xml"
          targetdir: "$GITHUB_WORKSPACE/report"
          historydir: "$GITHUB_WORKSPACE/history"
          reporttypes: 'MarkdownSummaryGithub;MarkdownDeltaSummary'

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: test-report
          recreate: true
          path: ./report/DeltaSummary.md
      
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: test-report
          append: true
          path: ./report/SummaryGithub.md
