name: Code coverage

on:
  pull_request:
    paths:
      - '**/*.cs'
      - '*'

jobs:
  dotnet-cc:

    runs-on: ubuntu-latest

    services:
      fauna:
        image: fauna/faunadb
        ports:
          - 8443:8443

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run tests w/ code coverage
        run: dotnet test --no-build --framework net8.0 --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput='./TestResults/'
      - name: Install ReportGenerator
        run: dotnet new tool-manifest && dotnet tool install dotnet-reportgenerator-globaltool
      - name: Generate CC report
        run: dotnet reportgenerator "-reports:./Fauna.Test/TestResults/coverage.net8.0.opencover.xml" "-targetdir:./report" "-reporttypes:MarkdownSummaryGithub"
      - name: Store markdown report as output
        id: report_md
        run: |
          echo "::set-output name=markdown::$(<./report/SummaryGithub.md)"

      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: test-report
          recreate: true
          message: |
            "${{ steps.report_md.outputs.markdown }}"
